/* EE20 Simulator — the 22 circuits: bilingual text + layouts (grid units, 1 u = 20 px).
   Layout conventions follow the instruction book: PNP transistors, top rail = battery −, bottom rail = battery +. */
window.EE20 = window.EE20 || {};

(function (EE) {
  'use strict';

  // ---- layout helpers ------------------------------------------------------
  const W = (...p) => ({ t: 'W', p });
  const WI = (...p) => ({ t: 'W', p, ins: true });          // insulated (red) wire
  const J = (...p) => ({ t: 'J', p });
  const R = (id, a, b, v, o) => Object.assign({ t: 'R', id, a, b, v }, o);
  const C = (id, a, b, v, o) => Object.assign({ t: 'C', id, a, b, v }, o);
  const CE = (id, a, b, v, plus, o) => Object.assign({ t: 'CE', id, a, b, v, plus }, o);
  const T = (id, x, y, typ, o) => Object.assign({ t: 'T', id, x, y, typ }, o);
  const POT = (id, a, b, w, v, o) => Object.assign({ t: 'P', id, a, b, w, v }, o);
  const D = (id, a, b, o) => Object.assign({ t: 'D', id, a, b }, o);
  const L = (id, a, b, o) => Object.assign({ t: 'L', id, a, b }, o);
  const LDR = (id, a, b, o) => Object.assign({ t: 'LDR', id, a, b }, o);
  const LAMP = (id, a, b, o) => Object.assign({ t: 'LAMP', id, a, b }, o);
  const SPK = (id, a, b, o) => Object.assign({ t: 'SPK', id, a, b }, o);
  const EAR = (id, a, b, o) => Object.assign({ t: 'EAR', id, a, b }, o);
  const MIC = (id, a, b, o) => Object.assign({ t: 'MIC', id, a, b }, o);
  const PU = (id, a, b, o) => Object.assign({ t: 'PU', id, a, b }, o);
  const KEY = (id, a, b, o) => Object.assign({ t: 'KEY', id, a, b }, o);
  const SW = (id, a, b, o) => Object.assign({ t: 'SW', id, a, b }, o);
  const SL = (id, c, a, b, o) => Object.assign({ t: 'SL', id, c, a, b }, o);
  const VC = (id, a, b, o) => Object.assign({ t: 'VC', id, a, b }, o);
  const BAT = (a, b) => ({ t: 'BAT', id: 'B', a, b });
  const TXT = (at, s, o) => Object.assign({ t: 'TXT', at, s }, o);
  const TERM = (at, s, o) => Object.assign({ t: 'TERM', at, s }, o);
  // battery + on/off switch on the right-hand side: x = battery column, rails y=1 (−) and y=19 (+)
  const PSU = (x, o) => [BAT([x, 1], [x, 19]), SW('S1S2', [x - 4, 19], [x - 2, 19]), W([x - 2, 19], [x, 19]),
    TXT([x - 4, 20.2], 'S1', { cls: 'small' }), TXT([x - 2, 20.2], 'S2', { cls: 'small' })];

  const k = 1000, u = 1e-6, n = 1e-9, p = 1e-12;

  const CIRCUITS = [];
  function add(c) { CIRCUITS.push(c); }

  // =========================================================================== A
  add({
    id: 'A1', group: 'A', ee8: true, pages: '15–16, 62',
    name: { en: 'Two-transistor gramophone amplifier', pt: 'Amplificador de dois transistores para toca-discos' },
    text: {
      desc: { en: 'Reproduces gramophone records clearly and powerfully through an earphone, so you can play records without disturbing other people. The pick-up of a record player is connected to the two terminals at the left; the earphone to the two terminals at the right.',
        pt: 'Reproduz discos com clareza e potência num fone de ouvido, de modo que você pode ouvir discos sem incomodar ninguém. O pick-up do toca-discos é ligado aos dois terminais da esquerda; o fone de ouvido, aos dois da direita.' },
      assembly: { en: 'Use wiring diagram A1. Fit hair-pins in all holes except S1+P1, P2 and P3, then springs. Mount the polyester and electrolytic capacitors first (watch the + groove), then the transistors (AF 116 on the left, AC 126 with its heat sink on the right), the bare wires, the earphone and the resistors. Insulated wires run from P3 to C2, from C5 to P2 and from the batteries to B− and S2.',
        pt: 'Use o esquema de fiação A1. Coloque grampos em todos os furos, exceto S1+P1, P2 e P3, depois as molas. Monte primeiro os capacitores de poliéster e eletrolíticos (atenção à ranhura +), depois os transistores (AF 116 à esquerda, AC 126 com dissipador à direita), os fios nus, o fone e os resistores. Fios encapados vão de P3 a C2, de C5 a P2 e das pilhas a B− e S2.' },
      use: { en: 'Connect the record player to the pick-up terminals (screen to the right-hand terminal). Put on a record, switch the amplifier on by turning the potentiometer knob to the right and set the volume with the same knob. If nothing is heard, go to “Checking for faults”.',
        pt: 'Ligue o toca-discos aos terminais do pick-up (blindagem no terminal da direita). Ponha um disco, ligue o amplificador girando o botão do potenciômetro para a direita e ajuste o volume com o mesmo botão. Se nada for ouvido, consulte “Localização de defeitos”.' },
      theory: { en: 'The alternating voltage generated by the needle sends a small alternating current through the base of T1. A much larger current flows in its collector circuit, and part of it reaches the potentiometer through C2. From the sliding contact a fraction goes through C4 to the base of T2, where it is amplified again. The collector current of T2 flows through C7 to the earphone and is hundreds of times stronger than the current from the pick-up.',
        pt: 'A tensão alternada gerada pela agulha faz circular uma pequena corrente alternada pela base de T1. Uma corrente muito maior circula no coletor, e parte dela chega ao potenciômetro através de C2. Do cursor, uma fração vai por C4 à base de T2, onde é amplificada de novo. A corrente de coletor de T2 passa por C7 até o fone e é centenas de vezes mais forte que a corrente do pick-up.' },
      apps: { en: 'Try a crystal and a magnetic pick-up; note the difference in volume. Turn the knob slowly and listen how the loudness follows the position of the sliding contact.', pt: 'Experimente um pick-up de cristal e um magnético; note a diferença de volume. Gire o botão devagar e ouça como o volume acompanha a posição do cursor.' },
    },
    controls: ['vol', 'gram'], outputs: ['ear', 'scope'],
    layout: { w: 34, h: 21, el: [
      W([8.5, 1], [13, 1]), R('R5', [13, 1], [16, 1], 270, { lab: 'l' }), W([16, 1], [32, 1]), W([1, 19], [28, 19]), ...PSU(32),
      PU('PU', [1, 19], [1, 9]), W([1, 9], [3, 9]), J([3, 9]), R('R1', [3, 9], [3, 19], 100 * k),
      C('C1', [3, 9], [5, 9], 0.1 * u, { lab: 'l' }), T('T1', 7, 9, 'AF116'),
      R('R2', [5, 9], [5, 5], 680 * k, { lab: 'l' }), W([5, 5], [8.5, 5]), R('R3', [8.5, 5], [8.5, 1], 4.7 * k), J([8.5, 5]), W([8.5, 7], [8.5, 5]), W([8.5, 11], [8.5, 19]), J([8.5, 19]),
      J([8.5, 6]), CE('C2', [8.5, 6], [11, 6], 10 * u, 'b', { lab: 'l' }), W([11, 6], [13, 6], [13, 7]),
      POT('R4', [13, 7], [13, 13], [15, 10], 10 * k, { lab: 'l' }), W([13, 13], [13, 19]), J([13, 19]),
      CE('C3', [11, 19], [11, 1], 100 * u, 'a'), J([11, 1], [11, 19]), CE('C5', [18, 19], [18, 1], 100 * u, 'a'), J([18, 1], [18, 19]),
      C('C4', [15, 10], [17, 10], 0.1 * u), T('T2', 19, 10, 'AC126'),
      R('R6', [17, 10], [17, 6], 330 * k, { lab: 'l' }), W([17, 6], [20.5, 6]), R('R7', [20.5, 6], [20.5, 1], 3.3 * k), J([20.5, 6]), W([20.5, 8], [20.5, 6]), W([20.5, 12], [20.5, 19]), J([20.5, 19]),
      J([20.5, 7]), CE('C7', [20.5, 7], [23, 7], 3.2 * u, 'b', { lab: 'l' }), W([23, 7], [23, 9]), EAR('EAR', [23, 9], [23, 15]), W([23, 15], [23, 19]), J([23, 19]),
      C('C6', [26, 19], [26, 1], 0.1 * u), J([26, 1], [26, 19]),
    ] },
  });

  add({
    id: 'A2', group: 'A', ee8: false, pages: '16–17, 62',
    name: { en: 'Audio amplifier (microphone and gramophone)', pt: 'Amplificador de áudio (microfone e toca-discos)' },
    text: {
      desc: { en: 'The big brother of A1: three transistors and reproduction through the loudspeaker. Besides the record player a microphone can be connected (the little earphone is used as a microphone). The sliding switch selects Microphone or Gramophone, and with an extra 27 000 Ω resistor speech and music can be mixed.',
        pt: 'O irmão maior do A1: três transistores e reprodução pelo alto-falante. Além do toca-discos pode-se ligar um microfone (o fone de ouvido é usado como microfone). A chave deslizante escolhe Microfone ou Toca-discos, e com um resistor extra de 27 000 Ω pode-se misturar fala e música.' },
      assembly: { en: 'Wiring diagram A2. Terminals in all holes except S1+P1, P2, P3, S3, S4 and S5. Mount components and wires; do not mix up the AC 126 and AF 116 transistors and never forget the heat sink on the right-hand AC 126. Connect the earphone where its symbol is drawn, the record player where the gramophone symbol is drawn.',
        pt: 'Esquema A2. Terminais em todos os furos, exceto S1+P1, P2, P3, S3, S4 e S5. Monte os componentes e fios; não troque os transistores AC 126 e AF 116 e nunca esqueça o dissipador do AC 126 da direita. Ligue o fone onde está o seu símbolo e o toca-discos onde está o símbolo do gramofone.' },
      use: { en: 'Slide the switch to the right for microphone reproduction, to the left for gramophone. You may hear a squeaking tone at position Microphone: hold the earphone further from the loudspeaker or turn the volume down — that is acoustic feedback.',
        pt: 'Chave à direita para reprodução do microfone, à esquerda para o toca-discos. Na posição Microfone pode surgir um apito: afaste o fone do alto-falante ou reduza o volume — é a realimentação acústica.' },
      theory: { en: 'With the switch at Gramophone the set works as A1, except that the output current now drives a loudspeaker via T3. At Microphone the transistor T1 comes into service as a preamplifier, because the microphone currents are much smaller than those from the pick-up.',
        pt: 'Com a chave em Toca-discos o aparelho funciona como o A1, só que a corrente de saída agora aciona um alto-falante por meio de T3. Em Microfone o transistor T1 entra em serviço como pré-amplificador, porque as correntes do microfone são muito menores que as do pick-up.' },
      apps: { en: 'Connect a 100 000 Ω resistor to S4 instead of S3: then you can talk through the music. Try shouting, whispering and blowing into the microphone.', pt: 'Ligue um resistor de 100 000 Ω em S4 em vez de S3: assim você pode falar por cima da música. Experimente gritar, sussurrar e soprar no microfone.' },
    },
    controls: ['vol', 'slide', 'gram', 'mic'], outputs: ['spk', 'scope'],
    layout: { w: 38, h: 21, el: [
      W([11.5, 1], [13, 1]), R('R4', [13, 1], [16, 1], 270, { lab: 'l' }), W([16, 1], [36, 1]), W([2, 19], [32, 19]), ...PSU(36),
      MIC('MIC', [2, 19], [2, 10]), R('R3', [6, 10], [6, 13], 27 * k), PU('PU', [6, 13], [6, 19]),
      SL('S3-S5', [4, 8], [2, 10], [6, 10], { la: 'mic', lb: 'gram' }), C('C1', [4, 8], [7, 8], 0.1 * u, { lab: 'l' }), W([7, 8], [8, 8]),
      T('T1', 10, 8, 'AF116'), R('R1', [8, 8], [8, 4], 680 * k, { lab: 'l' }), W([8, 4], [11.5, 4]), R('R2', [11.5, 4], [11.5, 1], 4.7 * k), J([11.5, 4]), W([11.5, 6], [11.5, 4]), W([11.5, 10], [11.5, 19]), J([11.5, 19]),
      J([11.5, 5]), CE('C2', [11.5, 5], [13.5, 5], 10 * u, 'b', { lab: 'l' }), W([13.5, 5], [16, 5], [16, 7]),
      CE('C3', [14.5, 19], [14.5, 1], 100 * u, 'a'), J([14.5, 1], [14.5, 19]),
      POT('R7', [16, 7], [16, 13], [18, 10], 10 * k, { lab: 'l' }), W([16, 13], [16, 19]), J([16, 19]),
      C('C4', [18, 10], [20, 10], 0.1 * u), T('T2', 22, 10, 'AC126'), R('R5', [20, 10], [20, 6], 330 * k, { lab: 'l' }), W([20, 6], [23.5, 6]), J([23.5, 6]),
      R('R6', [23.5, 6], [23.5, 1], 3.3 * k), W([23.5, 8], [23.5, 6]), W([23.5, 12], [23.5, 19]), J([23.5, 19]),
      J([23.5, 7]), CE('C5', [23.5, 7], [26, 7], 3.2 * u, 'b', { lab: 'l' }), W([26, 7], [27, 7], [27, 10]),
      T('T3', 29, 10, 'AC126'), R('R8', [27, 10], [27, 6], 27 * k, { lab: 'l' }), W([27, 6], [30.5, 6]), J([30.5, 6]), W([30.5, 8], [30.5, 6]), SPK('LS', [30.5, 6], [30.5, 1]), W([30.5, 12], [30.5, 19]), J([30.5, 19]),
      CE('C6', [33.5, 19], [33.5, 1], 100 * u, 'a'), J([33.5, 1]), W([32, 19], [33.5, 19]), J([33.5, 19]), W([33.5, 19], [32, 19]),
    ] },
  });

  add({
    id: 'A3', group: 'A', ee8: false, pages: '17, 63',
    name: { en: 'Push-pull audio amplifier', pt: 'Amplificador de áudio em “push-pull”' },
    text: {
      desc: { en: 'A gramophone amplifier giving greater volume and better reproduction than the previous one. Two loudspeakers are used, but it also works with one — it just does not play so loud.', pt: 'Um amplificador para toca-discos com mais volume e melhor reprodução que o anterior. Usam-se dois alto-falantes, mas também funciona com um só — apenas toca menos alto.' },
      assembly: { en: 'Diagram A3. The special point is that the two loudspeakers must be connected the same way round: the terminal with the red dot goes to the contact marked B−. The second loudspeaker is best mounted on a little baffle or box.', pt: 'Esquema A3. O detalhe especial é que os dois alto-falantes devem ser ligados no mesmo sentido: o terminal com o ponto vermelho vai ao contato marcado B−. O segundo alto-falante fica melhor montado numa pequena caixa.' },
      use: { en: 'Connect the record player and the two loudspeakers, switch on with the potentiometer. Compare the sound with A1 and A2.', pt: 'Ligue o toca-discos e os dois alto-falantes, ligue pelo potenciômetro. Compare o som com A1 e A2.' },
      theory: { en: 'T1 amplifies the pick-up current and drives T2; the collector current of T2 goes to the base of T3, but part of it flows directly across R7 and C5 through the loudspeakers. So the currents of two transistors pass through the loudspeakers, giving twice as much sound, and any excess of one is cancelled by a deficit of the other: less distortion.', pt: 'T1 amplifica a corrente do pick-up e excita T2; a corrente de coletor de T2 vai à base de T3, mas parte dela flui diretamente por R7 e C5 através dos alto-falantes. Assim as correntes de dois transistores passam pelos alto-falantes, dando o dobro de som, e qualquer excesso de um é cancelado pela falta do outro: menos distorção.' },
      apps: { en: 'Disconnect one loudspeaker and note how the volume drops. Put the second loudspeaker in another room with long wires.', pt: 'Desligue um alto-falante e note como o volume cai. Ponha o segundo alto-falante em outro cômodo com fios longos.' },
    },
    controls: ['vol', 'gram'], outputs: ['spk', 'spk2', 'scope'],
    layout: { w: 36, h: 21, el: [
      W([8.5, 1], [34, 1]), W([1, 19], [30, 19]), ...PSU(34),
      PU('PU', [1, 19], [1, 9]), W([1, 9], [3, 9]), J([3, 9]), R('R1', [3, 9], [3, 19], 100 * k),
      C('C1', [3, 9], [5, 9], 0.1 * u, { lab: 'l' }), T('T1', 7, 9, 'AF116'),
      R('R2', [5, 9], [5, 5], 680 * k, { lab: 'l' }), W([5, 5], [8.5, 5]), R('R3', [8.5, 5], [8.5, 1], 4.7 * k), J([8.5, 5]), W([8.5, 7], [8.5, 5]), W([8.5, 11], [8.5, 19]), J([8.5, 19]),
      J([8.5, 6]), CE('C2', [8.5, 6], [11, 6], 10 * u, 'b', { lab: 'l' }), W([11, 6], [12.5, 6], [12.5, 7]),
      POT('R4', [12.5, 7], [12.5, 13], [14.5, 10], 10 * k, { lab: 'l' }), W([12.5, 13], [12.5, 19]), J([12.5, 19]),
      C('C3', [14.5, 10], [16.5, 10], 0.1 * u), T('T2', 18.5, 10, 'AC126'), R('R5', [16.5, 10], [16.5, 6], 330 * k, { lab: 'l' }), W([16.5, 6], [20, 6]), J([20, 6]),
      R('R6', [20, 6], [20, 1], 3.3 * k), W([20, 8], [20, 6]), W([20, 12], [20, 19]), J([20, 19]),
      J([20, 7]), CE('C4', [20, 7], [22.5, 7], 3.2 * u, 'b', { lab: 'l' }), W([22.5, 7], [23.5, 7], [23.5, 10]), J([23.5, 7]),
      R('R7', [23.5, 7], [26, 7], 1.5 * k), CE('C5', [26, 7], [28.5, 7], 100 * u, 'b', { lab: 't' }), W([28.5, 7], [29.5, 7], [29.5, 4]),
      T('T3', 25.5, 10, 'AC126'), W([27, 8], [27, 6], [29.5, 6]), J([29.5, 6]), W([27, 12], [27, 19]), J([27, 19]),
      SPK('LS1', [28.5, 4], [28.5, 1], { lab: 'l' }), SPK('LS2', [31, 4], [31, 1]), W([29.5, 4], [28.5, 4]), W([29.5, 4], [31, 4]), J([29.5, 4]),
      CE('C6', [31.5, 19], [31.5, 10], 100 * u, 'a'), W([31.5, 10], [31.5, 6], [29.5, 6]), J([31.5, 19]), W([30, 19], [31.5, 19]),
    ] },
  });

  add({
    id: 'A4', group: 'A', ee8: false, pages: '17–18, 63',
    name: { en: 'Bi-Ampli amplifier', pt: 'Amplificador Bi-Ampli' },
    text: {
      desc: { en: 'A very interesting gramophone amplifier with two loudspeakers: one reproduces the low notes, the other the high notes. You hear the violins and the trumpets separately from the cellos and the drums, which makes the music more pleasant and more real — a pseudo-stereophonic effect.', pt: 'Um amplificador para toca-discos muito interessante com dois alto-falantes: um reproduz as notas graves, o outro as agudas. Ouvem-se os violinos e trompetes separados dos violoncelos e tambores, o que torna a música mais agradável e real — um efeito pseudoestereofônico.' },
      assembly: { en: 'Diagram A4. The loudspeaker on the mounting board reproduces the low notes (bass clef symbol). The high-note loudspeaker (treble clef) is connected with two insulated wires and does not need a baffle; its wires can be a yard long so that it stands well apart from the low-note loudspeaker.', pt: 'Esquema A4. O alto-falante da chapa reproduz os graves (símbolo da clave de fá). O alto-falante dos agudos (clave de sol) é ligado com dois fios encapados e não precisa de caixa; seus fios podem ter um metro, para ficar bem afastado do alto-falante dos graves.' },
      use: { en: 'Play a record with a full orchestra. Move the treble loudspeaker around the room and notice the spatial spread of the sound.', pt: 'Toque um disco com orquestra completa. Mova o alto-falante dos agudos pela sala e perceba a distribuição espacial do som.' },
      theory: { en: 'After T1 the currents go two ways: across C3 to T2 and across R5 to T3. Because of C3 only the high notes are amplified by T2 and reach the treble loudspeaker; C4 lets only the low notes reach T3 and the bass loudspeaker. Two amplifiers, one for the high and one for the low notes: a “Bi-Ampli”.', pt: 'Depois de T1 as correntes seguem dois caminhos: por C3 até T2 e por R5 até T3. Por causa de C3 só as notas agudas são amplificadas por T2 e chegam ao alto-falante de agudos; C4 só deixa passar as graves para T3 e o alto-falante de graves. Dois amplificadores, um para agudos e outro para graves: um “Bi-Ampli”.' },
      apps: { en: 'Swap C3 for a 10 µF electrolytic: the treble channel now also passes the low notes. Listen with headphones to the simulator: bass on the left, treble on the right.', pt: 'Troque C3 por um eletrolítico de 10 µF: o canal de agudos passa também os graves. No simulador, ouça com fones: graves à esquerda, agudos à direita.' },
    },
    controls: ['vol', 'gram'], outputs: ['bass', 'treble', 'scope'],
    layout: { w: 36, h: 21, el: [
      W([12, 1], [34, 1]), W([1, 19], [30, 19]), ...PSU(34),
      TERM([1, 5], ''), TERM([1, 19], ''), PU('PU', [1, 19], [1, 5]), W([1, 5], [3, 5], [3, 7]), J([3, 5]),
      R('R1', [3, 5], [5.5, 5], 100 * k, { lab: 't' }), W([5.5, 5], [5.5, 19]),
      POT('R2', [3, 7], [3, 13], [5, 10], 10 * k, { lab: 'l' }), W([3, 13], [3, 19]), J([3, 19]), J([5.5, 19]),
      C('C1', [5, 10], [7.5, 10], 0.1 * u), T('T1', 9.5, 10, 'AF116'),
      R('R3', [7.5, 10], [7.5, 6], 680 * k, { lab: 'l' }), W([7.5, 6], [11, 6]), R('R4', [11, 6], [11, 1], 4.7 * k), J([11, 6]), W([11, 8], [11, 6]), W([11, 12], [11, 19]), J([11, 19]),
      J([11, 7]), CE('C2', [11, 7], [13.5, 7], 10 * u, 'b', { lab: 'b' }), W([13.5, 7], [14.5, 7]), J([14.5, 7]),
      C('C3', [14.5, 7], [14.5, 4], 0.1 * u, { lab: 'l' }), W([14.5, 4], [17, 4]), T('T2', 19, 4, 'AC126'), R('R6', [17, 4], [17, 1.5], 330 * k, { lab: 'l' }), W([17, 1.5], [20.5, 1.5]), W([20.5, 2], [20.5, 1.5]), J([20.5, 1.5]),
      SPK('LS2', [20.5, 1.5], [24, 1.5], { lab: 'b' }), W([24, 1.5], [24, 1]), J([24, 1]), W([20.5, 6], [20.5, 10]), J([20.5, 10]),
      R('R5', [14.5, 7], [14.5, 10], 27 * k, { lab: 'l' }), W([14.5, 10], [14.5, 13]), CE('C4', [14.5, 13], [17, 13], 10 * u, 'b', { lab: 'b' }), W([17, 13], [18, 13]),
      T('T3', 20, 13, 'AC126'), R('R7', [18, 13], [18, 10], 27 * k, { lab: 'l' }), W([18, 10], [20.5, 10]), W([21.5, 11], [21.5, 10]), J([21.5, 10]),
      W([20.5, 10], [21.5, 10]), R('R8', [21.5, 10], [24.5, 10], 1.5 * k, { lab: 't' }), W([24.5, 10], [26, 10], [26, 8]), SPK('LS1', [26, 8], [26, 1], { lab: 'r' }), J([26, 1]),
      W([21.5, 15], [21.5, 19]), J([21.5, 19]), W([20.5, 6], [20.5, 10]),
      CE('C5', [29, 19], [29, 1], 100 * u, 'a'), J([29, 1], [29, 19]),
    ] },
  });

  add({
    id: 'A5', group: 'A', ee8: false, pages: '18–19, 64',
    name: { en: 'Electronic organ', pt: 'Órgão eletrônico' },
    text: {
      desc: { en: 'An electronic organ on which you can play a number of simple tunes. Eight keys give eight notes, and with the potentiometer the organ is tuned to a musical scale.', pt: 'Um órgão eletrônico no qual se podem tocar melodias simples. Oito teclas dão oito notas, e com o potenciômetro afina-se o órgão numa escala musical.' },
      assembly: { en: 'One of the most difficult sets — begin only after you have gained experience. Remove the lamp. The wiring diagram A5 is placed with the potentiometer and tuning capacitor at the back and the eight keys at the front. A bare wire runs through the front holes under all the keys. Mount the keys as shown on page 13.', pt: 'Uma das montagens mais difíceis — comece só depois de ganhar experiência. Retire a lâmpada. O esquema A5 é colocado com o potenciômetro e o capacitor variável atrás e as oito teclas na frente. Um fio nu passa pelos furos da frente sob todas as teclas. Monte as teclas como mostrado na página 13.' },
      use: { en: 'Press a key and you hear a note. Press keys 1 to 8 in succession: the notes get steadily higher. Turn the potentiometer until the scale sounds in tune (doh-ray-me-fah-soh-lah-te-doh). If you cannot get a reasonable scale, interchange C4 (0.1 µF) and C5 (47 000 pF). Get a recorder tutor or a school song book: doh is 1, ray is 2, and so on.', pt: 'Aperte uma tecla e ouvirá uma nota. Aperte as teclas 1 a 8 em sequência: as notas sobem. Gire o potenciômetro até a escala soar afinada (dó-ré-mi-fá-sol-lá-si-dó). Se não conseguir uma escala razoável, troque C4 (0,1 µF) por C5 (47 000 pF). Pegue um livro de canções escolares: dó é 1, ré é 2, e assim por diante.' },
      theory: { en: 'The notes are generated by T1 and T2, connected as a multivibrator like the flashing light D2 but running about a thousand times faster. Pressing a key sends base current of T1 through the resistors between the keys and R2 to the emitter of T1; the more resistance in the chain, the lower the note. R9 and C6 carry the tone to T3, which drives the loudspeaker. The pitch can be modified by the resistors R11–R17.', pt: 'As notas são geradas por T1 e T2, ligados como multivibrador, tal como o pisca-pisca D2, mas oscilando cerca de mil vezes mais depressa. Apertar uma tecla envia a corrente de base de T1 pelos resistores entre as teclas e R2 até o emissor de T1; quanto mais resistência na cadeia, mais grave a nota. R9 e C6 levam o tom a T3, que aciona o alto-falante. A afinação pode ser alterada pelos resistores R11–R17.' },
      apps: { en: 'Play “Frère Jacques”: 1 2 3 1 · 1 2 3 1 · 3 4 5 · 3 4 5. Press two keys at once and listen what happens.', pt: 'Toque “Frère Jacques”: 1 2 3 1 · 1 2 3 1 · 3 4 5 · 3 4 5. Aperte duas teclas ao mesmo tempo e ouça o que acontece.' },
    },
    controls: ['vol', 'keys'], outputs: ['spk', 'scope'],
    layout: { w: 40, h: 25, el: [
      W([3, 1], [38, 1]), W([1, 17], [34, 17]), BAT([38, 1], [38, 17]), SW('S7S8', [34, 17], [36, 17]), W([36, 17], [38, 17]), TXT([34, 18.2], 'S7', { cls: 'small' }), TXT([36, 18.2], 'S8', { cls: 'small' }),
      R('R1', [3, 1], [3, 6], 4.7 * k), W([3, 6], [3, 9], [5, 9]), J([3, 6]),
      T('T1', 7, 9, 'AF116'), R('R3', [5, 9], [5, 6], 680 * k, { lab: 'l' }), W([5, 6], [3, 6]), W([8.5, 7], [8.5, 5]), J([8.5, 5]),
      POT('R5', [8.5, 1], [8.5, 5], [10.5, 3], 10 * k, { lab: 'l' }), W([8.5, 1], [8.5, 1]),
      R('R6', [8.5, 5], [12, 5], 560, { lab: 't' }), J([12, 5]), R('R7', [12, 5], [12, 1], 3.3 * k), R('R8', [12, 5], [12, 8], 100 * k), W([12, 8], [12, 11], [13, 11]),
      W([8.5, 11], [8.5, 14], [1, 14]), R('R4', [1, 14], [1, 17], 15 * k, { lab: 'l' }), J([1, 17]),
      C('C1', [8.5, 6], [10.5, 6], 0.1 * u, { lab: 'b' }), W([10.5, 6], [10.5, 11]), J([8.5, 6]), J([10.5, 11]), W([10.5, 11], [12, 11]), J([12, 11]),
      W([5, 9], [5, 12]), C('C3', [5, 12], [8, 12], 47 * n, { lab: 'b' }), W([8, 12], [10.5, 12], [10.5, 11]),
      T('T2', 15, 11, 'AC126'), W([16.5, 9], [16.5, 5]), J([16.5, 5]), R('R9', [16.5, 5], [20, 5], 27 * k, { lab: 't' }), W([16.5, 5], [16.5, 1]), J([16.5, 1]),
      W([16.5, 13], [16.5, 17]), J([16.5, 17]),
      C('C4', [19, 1], [19, 4], 0.1 * u, { lab: 'r' }), W([19, 4], [19, 5]), J([19, 5]), W([20, 5], [21, 5], [21, 8]), C('C5', [21, 8], [21, 11], 47 * n, { lab: 'r' }), W([21, 11], [21, 17]), J([21, 17]),
      CE('C6', [21, 8], [24, 8], 3.2 * u, 'b', { lab: 't' }), J([21, 8]), W([24, 8], [25, 8]), T('T3', 27, 8, 'AC126'),
      R('R10', [25, 8], [25, 4], 27 * k, { lab: 'l' }), W([25, 4], [28.5, 4]), J([28.5, 4]), W([28.5, 6], [28.5, 4]), SPK('LS', [28.5, 4], [28.5, 1]), W([28.5, 10], [28.5, 17]), J([28.5, 17]),
      CE('C7', [31.5, 17], [31.5, 1], 100 * u, 'a'), J([31.5, 1], [31.5, 17]),
      // key chain
      W([1, 14], [1, 14]), R('R2', [3, 14], [3, 20], 120, { lab: 'l' }), W([3, 14], [1, 14]), J([3, 14]),
      W([3, 20], [4, 20]), J([4, 20]),
      R('R11', [4, 20], [7.5, 20], 180, { lab: 't', noval: true }), R('R12', [7.5, 20], [11, 20], 120, { lab: 't', noval: true }), R('R13', [11, 20], [14.5, 20], 220, { lab: 't', noval: true }), R('R14', [14.5, 20], [18, 20], 270, { lab: 't', noval: true }), R('R15', [18, 20], [21.5, 20], 270, { lab: 't', noval: true }), R('R16', [21.5, 20], [25, 20], 150, { lab: 't', noval: true }), R('R17', [25, 20], [28.5, 20], 120, { lab: 't', noval: true }),
      J([7.5, 20], [11, 20], [14.5, 20], [18, 20], [21.5, 20], [25, 20], [28.5, 20]),
      KEY('K1', [4, 20], [4, 23], { lab: 'l', noval: true }), KEY('K2', [7.5, 20], [7.5, 23]), KEY('K3', [11, 20], [11, 23]), KEY('K4', [14.5, 20], [14.5, 23]), KEY('K5', [18, 20], [18, 23]), KEY('K6', [21.5, 20], [21.5, 23]), KEY('K7', [25, 20], [25, 23]), KEY('K8', [28.5, 20], [28.5, 23]),
      W([4, 23], [28.5, 23]), W([28.5, 23], [30, 23], [30, 17]), J([30, 17]),
    ] },
  });

  // =========================================================================== B
  add({
    id: 'B1', group: 'B', ee8: true, pages: '20–21, 64',
    name: { en: 'Morse code training set', pt: 'Aparelho de treinamento em código Morse' },
    text: {
      desc: { en: 'When you depress the sending key you hear a whistling tone in the earphone — a short press is a dot, a longer one a dash. Every letter and figure has its own combination of dots and dashes; the Morse code is used all over the world in telegraphy and on the radio.', pt: 'Ao apertar o manipulador ouve-se um apito no fone — um toque curto é um ponto, um longo é um traço. Cada letra e algarismo tem a sua combinação de pontos e traços; o código Morse é usado no mundo inteiro na telegrafia e no rádio.' },
      assembly: { en: 'Diagram B1. Fix the terminals in all holes except P1+S1, P2, P3, A and B; the sending key sits on the long spring. Mount resistors, polyester and electrolytic capacitors (groove!), then the AC 126 (dot = collector) and the bare wires. Red wires: from C4 through hole P3 to P3 on the potentiometer; from C5 through P1+S1 to P1 and S1. A bare wire from C5 goes under the board from hole A to hole B.', pt: 'Esquema B1. Terminais em todos os furos, exceto P1+S1, P2, P3, A e B; o manipulador fica na mola comprida. Monte resistores, capacitores de poliéster e eletrolíticos (ranhura!), depois o AC 126 (ponto = coletor) e os fios nus. Fios vermelhos: de C4 pelo furo P3 até P3 do potenciômetro; de C5 por P1+S1 até P1 e S1. Um fio nu de C5 passa por baixo da chapa do furo A ao furo B.' },
      use: { en: 'Switch on with the potentiometer knob; press the key and you hear the tone. Begin slowly and increase the speed gradually. A friend can practise with you: a second key in parallel with the first, and several earphones in parallel for group training.', pt: 'Ligue pelo botão do potenciômetro; aperte o manipulador e ouvirá o tom. Comece devagar e aumente a velocidade aos poucos. Um amigo pode praticar com você: um segundo manipulador em paralelo com o primeiro e vários fones em paralelo para treino em grupo.' },
      theory: { en: 'A small base current of T1 causes a larger collector current, which crosses C1 and C2 back into the base, increasing it again — until the transistor suddenly stops. Then everything starts afresh, about a thousand times a second. Part of this rapidly changing collector current goes across C4 and the potentiometer to the earphone, where it creates a single note.', pt: 'Uma pequena corrente de base de T1 provoca uma corrente de coletor maior, que passa por C1 e C2 de volta à base, aumentando-a de novo — até que o transistor de repente para. Então tudo recomeça, cerca de mil vezes por segundo. Parte dessa corrente de coletor que muda rapidamente passa por C4 e pelo potenciômetro até o fone, onde cria uma nota única.' },
      apps: { en: 'Learn the code letter by letter; the table is on the Manual tab. Send your name. Practise receiving with the automatic friend of set B2.', pt: 'Aprenda o código letra por letra; a tabela está na aba do Manual. Envie o seu nome. Pratique recepção com o amigo automático do aparelho B2.' },
    },
    controls: ['vol', 'mkey'], outputs: ['ear', 'scope', 'decoder'],
    layout: { w: 32, h: 21, el: [
      W([4, 1], [30, 1]), W([4, 19], [26, 19]), ...PSU(30),
      C('C1', [4, 5], [8, 5], 47 * n, { lab: 't' }), W([4, 5], [4, 9]), J([4, 9]), W([8, 5], [10, 5]), J([10, 5]),
      C('C2', [4, 9], [7, 9], 47 * n, { lab: 't' }), J([7, 9]), C('C3', [7, 9], [10, 9], 47 * n, { lab: 't' }), R('R3', [10, 9], [13, 9], 4.7 * k, { lab: 't' }), J([13, 9]),
      R('R1', [4, 9], [4, 15], 4.7 * k, { lab: 'l' }), R('R2', [7, 9], [7, 15], 4.7 * k, { lab: 'l' }), W([4, 15], [4, 19]), W([7, 15], [7, 19]), J([4, 19], [7, 19]),
      R('R4', [10, 5], [10, 9], 680 * k, { lab: 'l' }), W([10, 5], [13, 5]), J([13, 5]), W([13, 9], [13, 9]),
      T('T1', 15, 9, 'AC126'), W([16.5, 7], [16.5, 5]), W([13, 5], [16.5, 5]), J([16.5, 5]), R('R5', [16.5, 5], [16.5, 1], 4.7 * k), W([16.5, 11], [16.5, 19]), J([16.5, 19]),
      J([16.5, 6]), CE('C4', [16.5, 6], [19.5, 6], 10 * u, 'b', { lab: 't' }), W([19.5, 6], [21, 6], [21, 7]),
      POT('R6', [21, 7], [21, 13], [23, 10], 10 * k, { lab: 'l' }), W([21, 13], [21, 16]), KEY('MK', [21, 16], [24, 16], { lab: 'b' }), W([24, 16], [24, 19]), J([24, 19]),
      EAR('EAR', [23, 10], [23, 14], { lab: 'r' }), W([23, 14], [24, 14], [24, 16]), J([24, 16]),
      CE('C5', [27, 19], [27, 1], 100 * u, 'a'), J([27, 1]), W([26, 19], [27, 19]), J([27, 19]), W([27, 19], [26, 19]),
    ] },
  });

  add({
    id: 'B2', group: 'B', ee8: false, pages: '21–22, 65',
    name: { en: 'Morse code trainer with loudspeaker', pt: 'Aparelho de telegrafia Morse com alto-falante' },
    text: {
      desc: { en: 'The same as B1, but the Morse signalling is reproduced through a loudspeaker so that a whole group can hear it. Two-way telegraphy is possible with a send-receive switch, a second key and a second loudspeaker in another room.', pt: 'Igual ao B1, mas a sinalização Morse é reproduzida num alto-falante, para que um grupo inteiro possa ouvi-la. É possível a telegrafia em duas vias com uma chave transmite-recebe, um segundo manipulador e um segundo alto-falante em outro cômodo.' },
      assembly: { en: 'Diagram B2; carry out the mounting as for B1 and add the second AC 126 with its heat sink. Connect the loudspeaker to the two terminals near its symbol. For the two-way switch, connect S7 to the loudspeaker terminal and the second loudspeaker with its key to S6.', pt: 'Esquema B2; faça a montagem como no B1 e acrescente o segundo AC 126 com dissipador. Ligue o alto-falante aos dois terminais junto ao seu símbolo. Para a chave de duas vias, ligue S7 ao terminal do alto-falante e o segundo alto-falante com o seu manipulador a S6.' },
      use: { en: 'With the switch to the right you hear what your friend is tapping; to the left your friend hears you. Do not connect more than two loudspeakers, or the AC 126 may be damaged.', pt: 'Com a chave à direita você ouve o que o seu amigo transmite; à esquerda o amigo ouve você. Não ligue mais de dois alto-falantes, ou o AC 126 pode ser danificado.' },
      theory: { en: 'The tone is generated as in B1. The alternating current in the collector of T1 goes through C6 to the base of T2, which amplifies it once more, and the collector current of T2 flows through the loudspeaker.', pt: 'O tom é gerado como no B1. A corrente alternada no coletor de T1 passa por C6 até a base de T2, que a amplifica outra vez, e a corrente de coletor de T2 circula pelo alto-falante.' },
      apps: { en: 'Use the built-in “friend” to send you a text at a chosen speed and write down what you hear. Then answer with your own key.', pt: 'Use o “amigo” embutido para lhe enviar um texto na velocidade escolhida e anote o que ouvir. Depois responda com o seu manipulador.' },
    },
    controls: ['vol', 'mkey', 'twoway', 'friend'], outputs: ['spk', 'spk2', 'scope', 'decoder'],
    layout: { w: 34, h: 21, el: [
      W([4, 1], [32, 1]), W([4, 19], [28, 19]), ...PSU(32),
      C('C1', [4, 5], [8, 5], 47 * n, { lab: 't' }), W([4, 5], [4, 9]), J([4, 9]), W([8, 5], [10, 5]), J([10, 5]),
      C('C2', [4, 9], [7, 9], 47 * n, { lab: 't' }), J([7, 9]), C('C3', [7, 9], [10, 9], 47 * n, { lab: 't' }), R('R3', [10, 9], [13, 9], 4.7 * k, { lab: 't' }), J([13, 9]),
      R('R1', [4, 9], [4, 15], 4.7 * k, { lab: 'l' }), R('R2', [7, 9], [7, 15], 4.7 * k, { lab: 'l' }), W([4, 15], [4, 19]), W([7, 15], [7, 19]), J([4, 19], [7, 19]),
      R('R4', [10, 5], [10, 9], 680 * k, { lab: 'l' }), W([10, 5], [13, 5]), J([13, 5]),
      T('T1', 15, 9, 'AC126'), W([16.5, 7], [16.5, 5]), W([13, 5], [16.5, 5]), J([16.5, 5]), R('R5', [16.5, 5], [16.5, 1], 4.7 * k), W([16.5, 11], [16.5, 19]), J([16.5, 19]),
      J([16.5, 6]), CE('C4', [16.5, 6], [19.5, 6], 10 * u, 'b', { lab: 't' }), W([19.5, 6], [20.5, 6], [20.5, 7]),
      POT('R6', [20.5, 7], [20.5, 13], [22.5, 10], 10 * k, { lab: 'l' }), W([20.5, 13], [20.5, 16]), KEY('MK', [20.5, 16], [23.5, 16], { lab: 'b' }), W([23.5, 16], [23.5, 19]), J([23.5, 19]),
      C('C6', [22.5, 10], [24.5, 10], 0.1 * u, { lab: 't' }), T('T2', 26.5, 10, 'AC126'), R('R7', [24.5, 10], [24.5, 6], 27 * k, { lab: 'l' }), W([24.5, 6], [28, 6]), J([28, 6]), W([28, 8], [28, 6]),
      SL('S6-S8', [28, 4], [26.5, 2.5], [29.5, 2.5], { la: 'rx', lb: 'tx' }), W([28, 6], [28, 4]), SPK('LS', [29.5, 2.5], [29.5, 1], { lab: 'r' }), W([26.5, 2.5], [26.5, 1]), J([26.5, 1]), J([29.5, 1]),
      W([28, 12], [28, 19]), J([28, 19]),
      CE('C7', [30.5, 19], [30.5, 8], 100 * u, 'a'), W([30.5, 8], [30.5, 1]), J([30.5, 1]), J([30.5, 19]), W([28, 19], [30.5, 19]),
    ] },
  });

  add({
    id: 'B3', group: 'B', ee8: false, pages: '22–24, 65',
    name: { en: 'Intercom (loudspeaker house telephone)', pt: 'Intercomunicador (telefone caseiro com alto-falantes)' },
    text: {
      desc: { en: 'A loudspeaker house telephone as used in factories, offices and shops. Two-way contact is possible over quite a large distance; speech is reproduced by loudspeakers and the volume is adjustable. The sliding switch selects speak or listen.', pt: 'Um telefone caseiro com alto-falantes, como os usados em fábricas, escritórios e lojas. Permite contato em duas vias a boa distância; a fala é reproduzida por alto-falantes e o volume é ajustável. A chave deslizante escolhe falar ou ouvir.' },
      assembly: { en: 'A fairly complicated set — do not begin with it. Diagram B3, terminals in all holes except S1+P1, P2, P3, S3+S8, S5+S6, S4 and S7. The insulated wire from the emitter/screen of the AF 116 goes under the board from S3+S8 to S3 and S8. The second loudspeaker is connected with a pair of long wires (two-core flex).', pt: 'Uma montagem bastante complicada — não comece por ela. Esquema B3, terminais em todos os furos, exceto S1+P1, P2, P3, S3+S8, S5+S6, S4 e S7. O fio encapado do emissor/blindagem do AF 116 passa por baixo da chapa de S3+S8 a S3 e S8. O segundo alto-falante é ligado com um par de fios longos.' },
      use: { en: 'Set the sliding switch to the left and speak into the loudspeaker on the set: your voice is heard from the other loudspeaker. Slide to the right and your friend in the other room can talk to you. Say “over” when you have finished, as in radio telephony.', pt: 'Ponha a chave à esquerda e fale no alto-falante do aparelho: a sua voz sai no outro alto-falante. Passe à direita e o amigo no outro cômodo pode falar com você. Diga “câmbio” ao terminar, como na radiotelefonia.' },
      theory: { en: 'When the switch is to the left the loudspeaker in the set works as a microphone: it supplies little currents corresponding to what you say. These flow through T1, the potentiometer, T2 and T3, growing stronger at each stage, and finally through the second loudspeaker, which reproduces loud and clear what was said into the first.', pt: 'Com a chave à esquerda o alto-falante do aparelho funciona como microfone: fornece pequenas correntes correspondentes ao que você diz. Elas passam por T1, pelo potenciômetro, por T2 e T3, ficando mais fortes a cada estágio, e finalmente pelo segundo alto-falante, que reproduz alto e claro o que foi dito no primeiro.' },
      apps: { en: 'Baby-sitter: hang the loudspeaker above the cradle. Front door: place a loudspeaker outside — but not in the rain. Radio play: produce sound effects with paper, sticks and glass marbles.', pt: 'Babá eletrônica: pendure o alto-falante sobre o berço. Porta da rua: ponha um alto-falante do lado de fora — mas não na chuva. Radioteatro: faça efeitos sonoros com papel, gravetos e bolinhas de gude.' },
    },
    controls: ['vol', 'slide', 'intercom'], outputs: ['spk', 'spk2', 'scope'],
    layout: { w: 38, h: 22, el: [
      W([9, 1], [12, 1]), R('R4', [12, 1], [15, 1], 270, { lab: 'l' }), W([15, 1], [36, 1]), W([1, 19], [32, 19]), ...PSU(36),
      CE('C2', [4, 19], [4, 13], 10 * u, 'a', { lab: 'r' }), W([4, 13], [4, 9]), J([4, 19]),
      T('T1', 6, 9, 'AF116'), R('R1', [4, 9], [4, 5], 680 * k, { lab: 'l' }), W([4, 5], [7.5, 5]), J([7.5, 5]), R('R2', [7.5, 5], [7.5, 1], 4.7 * k), W([7.5, 7], [7.5, 5]), W([7.5, 11], [7.5, 19]), J([7.5, 19]),
      C('C1', [1, 1], [1, 5], 0.1 * u, { lab: 'r' }), W([1, 1], [9, 1]), W([1, 5], [1, 9], [4, 9]), J([4, 9]),
      J([7.5, 6]), CE('C3', [7.5, 6], [10, 6], 10 * u, 'b', { lab: 'b' }), W([10, 6], [11, 6], [11, 7]),
      POT('R3', [11, 7], [11, 13], [13, 10], 10 * k, { lab: 'l' }), W([11, 13], [11, 19]), J([11, 19]),
      CE('C4', [13, 19], [13, 1], 100 * u, 'a'), J([13, 1], [13, 19]), W([13, 19], [13, 19]),
      C('C6', [13, 10], [15.5, 10], 0.1 * u, { lab: 'b' }), T('T2', 17.5, 10, 'AC126'), R('R5', [15.5, 10], [15.5, 6], 330 * k, { lab: 'l' }), W([15.5, 6], [19, 6]), J([19, 6]), R('R6', [19, 6], [19, 1], 3.3 * k), W([19, 8], [19, 6]), W([19, 12], [19, 19]), J([19, 19]),
      J([19, 7]), CE('C7', [19, 7], [21.5, 7], 3.2 * u, 'b', { lab: 'b' }), W([21.5, 7], [22.5, 7], [22.5, 10]), T('T3', 24.5, 10, 'AC126'), R('R7', [22.5, 10], [22.5, 6], 27 * k, { lab: 'l' }), W([22.5, 6], [26, 6]), J([26, 6]), R('R8', [26, 6], [26, 1], 1.5 * k), W([26, 8], [26, 6]), W([26, 12], [26, 19]), J([26, 19]),
      J([26, 7]), CE('C8', [26, 7], [28.5, 7], 100 * u, 'b', { lab: 'b' }), W([28.5, 7], [29.5, 7], [29.5, 13]),
      // speak/listen switch: common from T3 output (right) and input (left)
      SL('S3-S8', [29.5, 15], [27.5, 17], [31.5, 17], { la: 'talk', lb: 'listen' }), W([29.5, 13], [29.5, 15]),
      SPK('LS1', [27.5, 17], [27.5, 21], { lab: 'l' }), SPK('LS2', [31.5, 17], [31.5, 21], { lab: 'r' }), W([27.5, 21], [1, 21], [1, 9]), W([31.5, 21], [33.5, 21], [33.5, 19]), J([33.5, 19]), W([32, 19], [33.5, 19]),
      CE('C5', [33.5, 19], [33.5, 1], 100 * u, 'a'), J([33.5, 1]),
    ] },
  });

  add({
    id: 'B4', group: 'B', ee8: false, pages: '24–25, 65',
    name: { en: 'Telephone amplifier / monitoring set', pt: 'Amplificador telefônico / aparelho de escuta' },
    text: {
      desc: { en: 'A particularly sensitive microphone amplifier that captures very slight sounds and reproduces them clearly through the loudspeaker. With the choke used as a pick-up coil placed near a telephone, the whole room can hear a telephone conversation.', pt: 'Um amplificador de microfone particularmente sensível que capta sons muito fracos e os reproduz com clareza no alto-falante. Com a bobina de choque usada como bobina captadora perto de um telefone, a sala inteira ouve a conversa.' },
      assembly: { en: 'Diagram B4; leave S1+P1, P2, P3, S4, S3 and S5 free. Connect the loudspeaker; the earphone (used as microphone) to the second and fourth terminals from the left at the bottom. Take the choke coil, remove half an inch of insulation from its two leads and connect them to the first and fourth terminals.', pt: 'Esquema B4; deixe livres S1+P1, P2, P3, S4, S3 e S5. Ligue o alto-falante; o fone (usado como microfone) ao segundo e ao quarto terminais da esquerda, embaixo. Pegue a bobina de choque, desencape um centímetro dos seus dois fios e ligue-os ao primeiro e ao quarto terminais.' },
      use: { en: 'Slide to the right for the microphone: speak gently and it is heard through the loudspeaker; hang the microphone out of the window and you hear the birds. Slide to the left, put the coil near the telephone and call a friend: what he says is heard by everybody. Find the best position of the coil by trial and error.', pt: 'Chave à direita para o microfone: fale baixinho e será ouvido no alto-falante; pendure o microfone na janela e ouvirá os pássaros. Chave à esquerda, ponha a bobina perto do telefone e ligue para um amigo: o que ele diz todos ouvem. Ache a melhor posição da bobina por tentativas.' },
      theory: { en: 'The magnetic fields inside the telephone induce little voltages in the pick-up coil; these currents are amplified three times in succession by T1, T2 and T3 until they are strong enough to drive the loudspeaker. With the switch to the right the microphone currents take the place of the coil currents.', pt: 'Os campos magnéticos dentro do telefone induzem pequenas tensões na bobina captadora; essas correntes são amplificadas três vezes seguidas por T1, T2 e T3 até serem fortes o bastante para acionar o alto-falante. Com a chave à direita as correntes do microfone tomam o lugar das da bobina.' },
      apps: { en: 'Noise meter: the whistling (feedback) tells you the microphone is too near the loudspeaker. Listen to a watch ticking through the microphone.', pt: 'Medidor de ruído: o apito (realimentação) avisa que o microfone está perto demais do alto-falante. Ouça o tique-taque de um relógio pelo microfone.' },
    },
    controls: ['vol', 'slide', 'pickup'], outputs: ['spk', 'scope'],
    layout: { w: 38, h: 22, el: [
      W([9, 1], [12, 1]), R('R4', [12, 1], [15, 1], 270, { lab: 'l' }), W([15, 1], [36, 1]), W([1, 19], [32, 19]), ...PSU(36),
      L('L1', [1, 19], [1, 9], { turns: 5, lab: 'l' }), SL('S3-S5', [3, 12], [1, 14], [5, 14], { la: 'coil', lb: 'mic' }), W([3, 12], [3, 9]), W([1, 9], [3, 9]), J([3, 9]),
      MIC('MIC', [5, 14], [5, 19], { lab: 'r' }), J([5, 19]), J([1, 19]), W([1, 14], [1, 14]),
      CE('C1', [3, 9], [3, 5], 10 * u, 'a', { lab: 'l' }), W([3, 5], [4, 5], [4, 9]),
      T('T1', 6, 9, 'AF116'), R('R1', [4, 9], [4, 4], 680 * k, { lab: 'r' }), W([4, 4], [7.5, 4]), J([7.5, 4]), R('R2', [7.5, 4], [7.5, 1], 4.7 * k), W([7.5, 7], [7.5, 4]), W([7.5, 11], [7.5, 19]), J([7.5, 19]),
      J([7.5, 6]), CE('C2', [7.5, 6], [10, 6], 10 * u, 'b', { lab: 'b' }), W([10, 6], [11, 6], [11, 7]),
      POT('R3', [11, 7], [11, 13], [13, 10], 10 * k, { lab: 'l' }), W([11, 13], [11, 19]), J([11, 19]),
      CE('C3', [13, 19], [13, 1], 100 * u, 'a'), J([13, 1], [13, 19]),
      C('C5', [13, 10], [15.5, 10], 0.1 * u, { lab: 'b' }), T('T2', 17.5, 10, 'AC126'), R('R5', [15.5, 10], [15.5, 6], 330 * k, { lab: 'l' }), W([15.5, 6], [19, 6]), J([19, 6]), R('R6', [19, 6], [19, 1], 3.3 * k), W([19, 8], [19, 6]), W([19, 12], [19, 19]), J([19, 19]),
      J([19, 7]), CE('C6', [19, 7], [21.5, 7], 3.2 * u, 'b', { lab: 'b' }), W([21.5, 7], [22.5, 7], [22.5, 10]), T('T3', 24.5, 10, 'AC126'), R('R7', [22.5, 10], [22.5, 6], 27 * k, { lab: 'l' }), W([22.5, 6], [26, 6]), J([26, 6]), W([26, 8], [26, 6]), SPK('LS', [26, 6], [26, 1]), W([26, 12], [26, 19]), J([26, 19]),
      CE('C4', [29, 19], [29, 1], 100 * u, 'a'), J([29, 1], [29, 19]),
    ] },
  });

  // =========================================================================== C
  const RADIO_FRONT = [ // shared reflex receiver front end (T1 AF 116 with aerial coil, diode and choke)
    W([2, 3], [2, 1]), L('L1', [2, 3], [2, 11], { turns: 6, lab: 'l' }), W([2, 11], [2, 13]), VC('C10', [4, 11], [4, 3], { lab: 'r' }), W([2, 3], [4, 3]), W([2, 11], [4, 11]), J([2, 3], [2, 11]),
    { t: 'ANT', at: [2, 1] }, { t: 'W', p: [[2, 13], [2, 19]], dash: true }, L('L2', [2, 13], [2, 17], { turns: 3, lab: 'l' }), W([2, 17], [2, 19]), J([2, 19]), { t: 'GND', at: [2, 19] },
    W([2, 13], [5, 13], [5, 11]), J([2, 13]), R('R1', [5, 11], [5, 7], 680 * k, { lab: 'r' }), W([5, 7], [5, 5], [11, 5]), J([5, 11]), W([5, 11], [6, 11]),
    T('T1', 8, 11, 'AF116'), W([9.5, 9], [9.5, 5]), J([9.5, 5]), W([9.5, 13], [9.5, 19]), J([9.5, 19]),
    C('C11', [11, 5], [11, 8], 47 * n, { lab: 'l' }), D('X1', [11, 8], [11, 11], { lab: 'l' }), W([11, 11], [11, 12]), C('C12', [11, 12], [11, 15], 0.1 * u, { lab: 'l' }), W([11, 15], [11, 19]), J([11, 19]), J([11, 5]), J([11, 11]),
    W([11, 11], [13, 11], [13, 8]), R('R2', [13, 8], [13, 1], 4.7 * k, { lab: 'r', noval: false }), L('L4', [13, 8], [13, 4], { turns: 3, lab: 'r' }), J([13, 8]),
    W([11, 5], [11, 5]), C('C13', [13, 11], [13, 15], 10 * u, { lab: 'r' }), W([13, 15], [13, 19]), J([13, 19]), J([13, 11]),
    R('R3', [15, 8], [15, 4], 15 * k, { lab: 'r' }), W([15, 4], [15, 1]), J([15, 1]), W([13, 8], [15, 8]), J([15, 8]),
  ];
  add({
    id: 'C1', group: 'C', ee8: true, pages: '25–29, 66',
    name: { en: 'Radio receiver with one transistor', pt: 'Receptor de rádio com um transistor' },
    text: {
      desc: { en: 'A medium-wave receiver with its own built-in aerial, listened to with an earphone. With an outside aerial and earth reception is much better; with an extra coil the trawler band can be received, and by turning the ferroxcube rod the set becomes a directional receiver.', pt: 'Um receptor de ondas médias com antena própria embutida, ouvido com fone. Com antena externa e terra a recepção é bem melhor; com uma bobina extra recebe-se a faixa dos pesqueiros, e girando o bastão de ferroxcube o aparelho vira um receptor direcional.' },
      assembly: { en: 'Diagram C1. Slide the aerial coil onto the ferroxcube rod, exactly in the middle, and mount the rod with rubber grommets. Red wire of the coil to the terminal near the tuning capacitor drawing, yellow wire to V2, green wire to the base of the AF 116 and grey wire to the point between the 47 000 pF capacitor and the OA 79 diode.', pt: 'Esquema C1. Enfie a bobina de antena no bastão de ferroxcube, bem no meio, e monte o bastão com as borrachas. Fio vermelho da bobina ao terminal junto ao desenho do capacitor variável, amarelo a V2, verde à base do AF 116 e cinza ao ponto entre o capacitor de 47 000 pF e o diodo OA 79.' },
      use: { en: 'Switch on with the potentiometer, turn the tuning knob slowly until you receive one or more stations. Turn the whole set: when the rod points exactly at the transmitter the station disappears. With two known transmitters you can find your own position on a map, like ships at sea.', pt: 'Ligue pelo potenciômetro e gire o botão de sintonia devagar até receber uma ou mais emissoras. Gire o aparelho inteiro: quando o bastão aponta exatamente para o transmissor a emissora some. Com dois transmissores conhecidos você acha a sua posição no mapa, como os navios no mar.' },
      theory: { en: 'Radio waves induce voltages in the aerial coil L1. Tuned by C10 it is in resonance with one transmitter only. Coupling coil L2 passes the signal to the base of T1, which amplifies it; the choke L4 blocks the high-frequency current, so it goes through C11 to the diode X1, which detects it. The low-frequency current flows back through L2 to the base and is amplified once more by the same transistor (a reflex receiver), then through C13 and the potentiometer to the earphone.', pt: 'As ondas de rádio induzem tensões na bobina L1. Sintonizada por C10, ela entra em ressonância com um só transmissor. A bobina de acoplamento L2 passa o sinal à base de T1, que o amplifica; a bobina de choque L4 bloqueia a corrente de alta frequência, que vai por C11 ao diodo X1, que a detecta. A corrente de baixa frequência volta por L2 à base e é amplificada de novo pelo mesmo transistor (receptor reflex), depois vai por C13 e pelo potenciômetro ao fone.' },
      apps: { en: 'Outside aerial: connect it to the top terminal, earth to the bottom one. Trawler band: wind a second coil of 28 turns and 2–3 more on the rod (60–180 m) and hear the fishing fleet. Direction finding: draw bearing lines to two transmitters.', pt: 'Antena externa: ligue ao terminal de cima, terra ao de baixo. Faixa dos pesqueiros: enrole uma segunda bobina de 28 espiras e mais 2–3 no bastão (60–180 m) e ouça a frota pesqueira. Radiogoniometria: trace linhas de marcação para dois transmissores.' },
    },
    controls: ['vol', 'tune', 'orient', 'aerial', 'trawler'], outputs: ['ear', 'scope', 'stations'],
    layout: { w: 30, h: 21, el: [
      ...RADIO_FRONT, W([13, 1], [28, 1]), W([2, 19], [24, 19]), ...PSU(28),
      W([15, 8], [17, 8], [17, 7]), C('C15', [17, 1], [17, 5], 0.1 * u, { lab: 'r' }), W([17, 5], [17, 7]), J([17, 1]),
      POT('R4', [17, 7], [17, 13], [19, 10], 10 * k, { lab: 'l' }), W([17, 13], [17, 19]), J([17, 19]),
      EAR('EAR', [19, 10], [19, 15], { lab: 'r' }), W([19, 15], [19, 19]), J([19, 19]),
      C('C14', [22, 19], [22, 12], 0.1 * u, { lab: 'r' }), W([22, 12], [22, 8], [17, 8]), J([22, 19]),
    ] },
  });
  add({
    id: 'C2', group: 'C', ee8: true, pages: '28, 66',
    name: { en: 'Two-transistor radio receiver', pt: 'Receptor de rádio com dois transistores' },
    text: {
      desc: { en: 'The same receiver with a second transistor, which makes it much more sensitive. Reception is again with the earphone; a large part of C2 is precisely the same as C1.', pt: 'O mesmo receptor com um segundo transistor, que o torna muito mais sensível. A recepção é de novo com fone; grande parte do C2 é exatamente igual ao C1.' },
      assembly: { en: 'Diagram C2. Read the C1 instructions again; a sensitive set needs every component accurately placed. C16 is the same value as C15 — an important difference in the wiring of a second transistor.', pt: 'Esquema C2. Releia as instruções do C1; um aparelho sensível exige cada componente colocado com exatidão. C16 tem o mesmo valor que C15 — uma diferença importante na fiação do segundo transistor.' },
      use: { en: 'If reception is too weak use an outside aerial. The set can also be used as a radio direction finder.', pt: 'Se a recepção for fraca use uma antena externa. O aparelho também pode ser usado como radiogoniômetro.' },
      theory: { en: 'Up to the potentiometer the circuit is identical to C1. The currents from the sliding contact now go to the base of T2, which amplifies the low-frequency currents; from its collector they flow across a capacitor to the earphone.', pt: 'Até o potenciômetro o circuito é idêntico ao C1. As correntes do cursor vão agora à base de T2, que amplifica as correntes de baixa frequência; do seu coletor elas passam por um capacitor até o fone.' },
      apps: { en: 'Compare the sensitivity with C1 on the weakest station you can find.', pt: 'Compare a sensibilidade com o C1 na emissora mais fraca que encontrar.' },
    },
    controls: ['vol', 'tune', 'orient', 'aerial'], outputs: ['ear', 'scope', 'stations'],
    layout: { w: 34, h: 21, el: [
      ...RADIO_FRONT, W([13, 1], [32, 1]), W([2, 19], [28, 19]), ...PSU(32),
      W([15, 8], [17, 8], [17, 7]), C('C15', [17, 1], [17, 5], 0.1 * u, { lab: 'l' }), W([17, 5], [17, 7]), J([17, 1]),
      POT('R5', [17, 7], [17, 13], [19, 10], 10 * k, { lab: 'l' }), W([17, 13], [17, 19]), J([17, 19]),
      C('C14', [19.5, 19], [19.5, 14], 0.1 * u, { lab: 'r' }), W([19.5, 14], [19.5, 12], [17, 12]), J([19.5, 19]), J([17, 12]),
      C('C17', [19, 10], [21, 10], 0.1 * u, { lab: 't' }), T('T2', 23, 10, 'AC126'), R('R6', [21, 10], [21, 6], 330 * k, { lab: 'l' }), W([21, 6], [24.5, 6]), J([24.5, 6]), R('R7', [24.5, 6], [24.5, 1], 3.3 * k), W([24.5, 8], [24.5, 6]), W([24.5, 12], [24.5, 19]), J([24.5, 19]),
      J([24.5, 7]), CE('C18', [24.5, 7], [27, 7], 3.2 * u, 'b', { lab: 'b' }), W([27, 7], [27, 9]), EAR('EAR', [27, 9], [27, 15], { lab: 'r' }), W([27, 15], [27, 19]), J([27, 19]),
      C('C16', [20, 1], [20, 4], 0.1 * u, { lab: 'r' }), W([20, 4], [20, 5], [17, 5]), J([20, 1]), J([17, 5]),
    ] },
  });
  add({
    id: 'C3', group: 'C', ee8: false, pages: '28–29, 67',
    name: { en: 'Three-transistor receiver with loudspeaker', pt: 'Receptor de três transistores com alto-falante' },
    text: {
      desc: { en: 'More powerful currents are needed for a loudspeaker than for an earphone, so a third transistor is added. Everything is more critical; if you have done everything right the set plays through the loudspeaker.', pt: 'Um alto-falante precisa de correntes mais fortes que um fone, por isso acrescenta-se um terceiro transistor. Tudo é mais crítico; se você fez tudo certo o aparelho toca pelo alto-falante.' },
      assembly: { en: 'Diagram C3. Do not forget the heat sink on the right-hand AC 126, otherwise the receiver gets weaker and weaker and the transistor may break down. Tilt the set and note how the tone improves.', pt: 'Esquema C3. Não esqueça o dissipador do AC 126 da direita, senão o receptor vai enfraquecendo e o transistor pode se danificar. Incline o aparelho e note como o som melhora.' },
      use: { en: 'Special application: an alarm which only rings when it is good weather! Connect the LDR between two terminals in the base circuit of the AC 126: in the dark the set is silent, when the sun rises it starts to play again.', pt: 'Aplicação especial: um despertador que só toca quando faz bom tempo! Ligue o LDR entre dois terminais no circuito de base do AC 126: no escuro o aparelho fica mudo, quando o sol nasce ele volta a tocar.' },
      theory: { en: 'Up to T2 the circuit is the C2 receiver. The collector currents of T2 flow through a capacitor to the base of T3 (with the heat sink), and its collector current is strong enough to drive the loudspeaker.', pt: 'Até T2 o circuito é o receptor C2. As correntes de coletor de T2 passam por um capacitor à base de T3 (com dissipador), e a corrente de coletor deste é forte o bastante para acionar o alto-falante.' },
      apps: { en: 'Sunrise alarm with the LDR (light slider in the simulator). Try the outside aerial for distant stations.', pt: 'Despertador solar com o LDR (controle de luz no simulador). Experimente a antena externa para emissoras distantes.' },
    },
    controls: ['vol', 'tune', 'orient', 'aerial', 'light'], outputs: ['spk', 'scope', 'stations'],
    layout: { w: 38, h: 21, el: [
      ...RADIO_FRONT, W([13, 1], [36, 1]), W([2, 19], [32, 19]), ...PSU(36),
      W([15, 8], [17, 8], [17, 7]), C('C15', [17, 1], [17, 5], 0.1 * u, { lab: 'l' }), W([17, 5], [17, 7]), J([17, 1]),
      POT('R5', [17, 7], [17, 13], [19, 10], 10 * k, { lab: 'l' }), W([17, 13], [17, 19]), J([17, 19]),
      C('C14', [19.5, 19], [19.5, 14], 0.1 * u, { lab: 'r' }), W([19.5, 14], [19.5, 12], [17, 12]), J([19.5, 19]), J([17, 12]),
      C('C17', [19, 10], [21, 10], 0.1 * u, { lab: 't' }), T('T2', 23, 10, 'AC126'), R('R6', [21, 10], [21, 6], 330 * k, { lab: 'l' }), W([21, 6], [24.5, 6]), J([24.5, 6]), R('R7', [24.5, 6], [24.5, 1], 3.3 * k), W([24.5, 8], [24.5, 6]), W([24.5, 12], [24.5, 19]), J([24.5, 19]),
      J([24.5, 7]), CE('C18', [24.5, 7], [27, 7], 3.2 * u, 'b', { lab: 'b' }), W([27, 7], [28, 7], [28, 10]), T('T3', 30, 10, 'AC126'), R('R8', [28, 10], [28, 6], 27 * k, { lab: 'l' }), W([28, 6], [31.5, 6]), J([31.5, 6]), W([31.5, 8], [31.5, 6]), SPK('LS', [31.5, 6], [31.5, 1]), W([31.5, 12], [31.5, 19]), J([31.5, 19]),
      C('C16', [20, 1], [20, 4], 0.1 * u, { lab: 'r' }), W([20, 4], [20, 5], [17, 5]), J([20, 1]), J([17, 5]),
    ] },
  });

  // =========================================================================== D
  add({
    id: 'D1', group: 'D', ee8: true, pages: '29–30, 67',
    name: { en: 'Tell-tale light', pt: 'Registrador de luz' },
    text: {
      desc: { en: 'Signals whether the light has been on in a room that is normally dark. As soon as a light goes on where the LDR is, the signalling lamp lights up — and stays on until the reset key is pressed, even if the room light was switched off again immediately.', pt: 'Indica se a luz foi acesa num cômodo normalmente escuro. Assim que uma luz acende onde está o LDR, a lâmpada de sinalização acende — e fica acesa até que a tecla de rearme seja apertada, mesmo que a luz do cômodo tenha sido apagada logo em seguida.' },
      assembly: { en: 'Diagram D1; springs everywhere except A, B, C, L and S1. Note the screening lead (1) of the AF 116 and the red dot of the AC 126. The lower bare wire runs under the board between A and B; pull it tight. Mount the LDR on the two springs bottom left with the stripes to the sensitive side.', pt: 'Esquema D1; molas em todos os furos, exceto A, B, C, L e S1. Note o terminal de blindagem (1) do AF 116 e o ponto vermelho do AC 126. O fio nu de baixo passa por baixo da chapa entre A e B; estique-o bem. Monte o LDR nas duas molas de baixo à esquerda, com as listras para o lado sensível.' },
      use: { en: 'Switch on; the lamp should light immediately. Put the light out in the room and press the reset key: the lamp goes out. Flash a torch round the room and see how sensitive your tell-tale light is. To react still faster replace R3 by 100 000 or 330 000 Ω.', pt: 'Ligue; a lâmpada deve acender logo. Apague a luz do cômodo e aperte o rearme: a lâmpada apaga. Passeie uma lanterna pela sala e veja como o registrador é sensível. Para reagir ainda mais depressa troque R3 por 100 000 ou 330 000 Ω.' },
      theory: { en: 'In the dark the LDR has a high resistance and T1 draws no current. The moment light falls on the LDR, current flows through T1 and, as a consequence, through the base of T2, so that the lamp in its collector circuit lights. Part of the lamp current is fed back through R3 to the base of T1, so T1 keeps conducting even when the light is gone; the reset key breaks this loop.', pt: 'No escuro o LDR tem resistência alta e T1 não conduz. No instante em que a luz cai sobre o LDR, circula corrente por T1 e, em consequência, pela base de T2, e a lâmpada no coletor acende. Parte da corrente da lâmpada é realimentada por R3 à base de T1, de modo que T1 continua conduzindo mesmo sem luz; a tecla de rearme interrompe esse laço.' },
      apps: { en: 'Put the set in your room and later you can see whether anybody has been there. Try covering the LDR with your hand before switching on.', pt: 'Deixe o aparelho no seu quarto e depois saberá se alguém entrou. Experimente cobrir o LDR com a mão antes de ligar.' },
    },
    controls: ['vol', 'light', 'rkey'], outputs: ['lamp', 'scope'],
    layout: { w: 28, h: 21, el: [
      W([4, 1], [26, 1]), W([2, 19], [22, 19]), ...PSU(26),
      R('R1', [4, 1], [4, 6], 3.3 * k, { lab: 'l' }), W([4, 6], [4, 8]), J([4, 6]), W([4, 6], [6, 6]), R('R2', [6, 6], [9.5, 6], 2.2 * k, { lab: 't' }), W([9.5, 6], [11, 6], [11, 10]),
      T('T1', 5.5, 10, 'AF116', { flip: true }), W([4, 12], [4, 19]), J([4, 19]),
      W([7.5, 10], [8, 10], [8, 12]), J([8, 12]), LDR('LDR', [8, 12], [8, 16], { lab: 'l' }), J([8, 16]), R('R4', [8, 16], [8, 19], 4.7 * k, { lab: 'l' }), J([8, 19]),
      W([8, 16], [10, 16]), CE('C1', [10, 16], [10, 19], 10 * u, 'b', { lab: 'r' }), J([10, 19]),
      R('R3', [8, 12], [11.5, 12], 27 * k, { lab: 'b' }), W([11.5, 12], [12.5, 12], [12.5, 15], [16, 15], [16, 7], [14.5, 7]), J([14.5, 7]),
      T('T2', 13, 10, 'AC126'), W([14.5, 8], [14.5, 6]), LAMP('LA', [14.5, 6], [14.5, 1], { lab: 'r' }), W([14.5, 12], [14.5, 14]), R('R5', [14.5, 14], [14.5, 19], 47, { lab: 'r' }), J([14.5, 19]),
      KEY('RK', [2, 19], [2, 14], { lab: 'r' }), W([2, 14], [2, 12], [8, 12]), J([2, 19]),
      CE('C2', [22, 19], [22, 1], 100 * u, 'a'), J([22, 1], [22, 19]),
    ] },
  });

  add({
    id: 'D2', group: 'D', ee8: true, pages: '30–31, 67–68',
    name: { en: 'Flashing light (Belisha beacon)', pt: 'Pisca-pisca (sinalizador)' },
    text: {
      desc: { en: 'A lamp flashes regularly on and off, like a Belisha beacon at a pedestrian crossing, police signs, traffic and display signs. Everything is done electronically — no moving parts.', pt: 'Uma lâmpada pisca regularmente, como um sinalizador de faixa de pedestres, letreiros de trânsito e anúncios. Tudo é feito eletronicamente — sem peças móveis.' },
      assembly: { en: 'Diagram D2. Fit terminals in all holes except those marked L and S1; the bare wires first, then the resistors, the electrolytic capacitors C1, C2 and C3 (groove towards the + mark), the AF 116 (dot = collector), the AC 126 with heat sink, and the lamp on the terminals near its symbol.', pt: 'Esquema D2. Terminais em todos os furos, exceto L e S1; primeiro os fios nus, depois os resistores, os eletrolíticos C1, C2 e C3 (ranhura para o +), o AF 116 (ponto = coletor), o AC 126 com dissipador, e a lâmpada nos terminais junto ao seu símbolo.' },
      use: { en: 'Switch on with the potentiometer knob. The lamp begins to flash on and off and keeps on doing this, if necessary for hours, until the battery is exhausted.', pt: 'Ligue pelo botão do potenciômetro. A lâmpada começa a piscar e continua assim, se necessário por horas, até as pilhas se esgotarem.' },
      theory: { en: 'A small current surge through the base of T1 causes a larger surge in its collector circuit, which crosses C1 to the base of T2: the lamp lights. A smaller part crosses C2 back to the base of T1 in such a way that T1 stops, and while the capacitors recharge through R3 and R4 the lamp goes out again. The circuit is a multivibrator; its speed depends on the capacitors and resistors.', pt: 'Uma pequena corrente na base de T1 provoca uma corrente maior no seu coletor, que passa por C1 à base de T2: a lâmpada acende. Uma parte menor volta por C2 à base de T1, de modo que T1 para, e enquanto os capacitores se recarregam por R3 e R4 a lâmpada apaga de novo. O circuito é um multivibrador; sua velocidade depende dos capacitores e resistores.' },
      apps: { en: 'Change C1 for a 10 µF capacitor and see the rhythm change. Build a model lighthouse with the lamp.', pt: 'Troque C1 por um capacitor de 10 µF e veja o ritmo mudar. Faça um farol de brinquedo com a lâmpada.' },
    },
    controls: ['vol'], outputs: ['lamp', 'scope'],
    layout: { w: 30, h: 21, el: [
      W([3, 1], [28, 1]), W([3, 19], [24, 19]), ...PSU(28),
      R('R1', [3, 1], [3, 5], 3.3 * k, { lab: 'l' }), W([3, 5], [3, 8]), J([3, 5]), W([3, 5], [8, 5]), J([8, 5]),
      T('T1', 4.5, 10, 'AF116', { flip: true }), W([3, 12], [3, 14]), R('R2', [3, 14], [3, 19], 47, { lab: 'l' }), J([3, 19]),
      W([6.5, 10], [8, 10]), J([8, 10]), R('R3', [8, 10], [8, 5], 27 * k, { lab: 'r' }), CE('C3', [8, 10], [8, 15], 10 * u, 'b', { lab: 'r' }), W([8, 15], [8, 19]), J([8, 19]),
      CE('C1', [8, 5], [12, 5], 10 * u, 'a', { lab: 't' }), W([12, 5], [17, 5], [17, 10]), J([17, 5]),
      W([8, 10], [8, 10]), CE('C2', [10, 10], [14, 10], 100 * u, 'b', { lab: 'b' }), W([8, 10], [10, 10]), W([14, 10], [14, 7], [17, 7]), J([17, 7]),
      R('R4', [17, 5], [17, 1], 15 * k, { lab: 'l' }), W([17, 5], [17, 10]),
      T('T2', 19, 10, 'AC126'), W([20.5, 8], [20.5, 6]), LAMP('LA', [20.5, 6], [20.5, 1], { lab: 'r' }), W([20.5, 12], [20.5, 14]), R('R5', [20.5, 14], [20.5, 19], 47, { lab: 'r' }), J([20.5, 19]), J([20.5, 7]), W([17, 7], [20.5, 7]),
      W([17, 7], [17, 7]), CE('C4', [24, 19], [24, 1], 100 * u, 'a'), J([24, 1], [24, 19]),
    ] },
  });

  add({
    id: 'D3', group: 'D', ee8: false, pages: '31–32, 68',
    name: { en: 'Acoustic relay', pt: 'Relé acústico' },
    text: {
      desc: { en: 'An electronic switch that turns on a lamp when a sound is made in a room. The sensitivity is adjustable, so a sound alarm can be activated by very slight sounds, or only when somebody slams a door.', pt: 'Uma chave eletrônica que acende uma lâmpada quando se faz um som num cômodo. A sensibilidade é ajustável, de modo que um alarme sonoro pode ser ativado por sons muito fracos ou só quando alguém bate a porta.' },
      assembly: { en: 'Diagram D3; lamp, potentiometer and batteries first. Terminals everywhere except A, B, C, S1+P1, P2 and P3. Bare wires A–B and C–C under the board. The insulated wire from the emitter of the AC 126 to R8 runs partly under the board. Mount the reset key (morse key) at the bottom left and connect the loudspeaker to the two terminals beside it: it works as microphone.', pt: 'Esquema D3; lâmpada, potenciômetro e pilhas primeiro. Terminais em toda parte, exceto A, B, C, S1+P1, P2 e P3. Fios nus A–B e C–C por baixo da chapa. O fio encapado do emissor do AC 126 a R8 corre em parte por baixo da chapa. Monte a tecla de rearme embaixo à esquerda e ligue o alto-falante aos dois terminais ao lado: ele funciona como microfone.' },
      use: { en: 'Put the loudspeaker down where you want to observe the sound. Turn the knob to the right until the lamp lights at a sound of the loudness you want. Press the reset key and the lamp goes out. Set it so that whoever slams the door will be fined!', pt: 'Ponha o alto-falante onde quer observar o som. Gire o botão para a direita até a lâmpada acender com um som da intensidade desejada. Aperte o rearme e a lâmpada apaga. Ajuste de modo que quem bater a porta seja multado!' },
      theory: { en: 'The sound received by the loudspeaker causes an alternating current, amplified by T1 and rectified by the diode X1. The rectified current flows to the base of T2 and upsets the balance of the flip-flop T2/T3: T3 begins to draw current and the lamp lights. It stays on until the reset key connects base and emitter of T3, just like the tell-tale light D1.', pt: 'O som recebido pelo alto-falante gera uma corrente alternada, amplificada por T1 e retificada pelo diodo X1. A corrente retificada vai à base de T2 e desequilibra o flip-flop T2/T3: T3 começa a conduzir e a lâmpada acende. Ela fica acesa até que o rearme ligue base e emissor de T3, exatamente como no registrador de luz D1.' },
      apps: { en: 'Noise meter: the lamp goes on when the sound in the room exceeds a set level, for instance when a baby cries. Use the real microphone of your computer in the simulator.', pt: 'Medidor de ruído: a lâmpada acende quando o som na sala passa de um nível ajustado, por exemplo quando um bebê chora. No simulador, use o microfone real do computador.' },
    },
    controls: ['vol', 'sound', 'rkey'], outputs: ['lamp', 'scope'],
    layout: { w: 34, h: 21, el: [
      W([5, 1], [32, 1]), W([2, 19], [28, 19]), ...PSU(32),
      SPK('LS', [2, 19], [2, 9], { lab: 'l' }), W([2, 9], [4, 9], [4, 7]), POT('R2', [4, 7], [4, 13], [6, 10], 10 * k, { lab: 'l' }), W([4, 13], [4, 19]), J([4, 19]), J([2, 19]),
      C('C1', [6, 10], [8, 10], 0.1 * u, { lab: 'b' }), T('T1', 10, 10, 'AC126'), R('R1', [8, 10], [8, 6], 330 * k, { lab: 'l' }), W([8, 6], [11.5, 6]), J([11.5, 6]), R('R3', [11.5, 6], [11.5, 1], 3.3 * k), W([11.5, 8], [11.5, 6]), W([11.5, 12], [11.5, 19]), J([11.5, 19]),
      J([11.5, 7]), C('C2', [11.5, 7], [14, 7], 0.1 * u, { lab: 'b' }), W([14, 7], [14.5, 7], [14.5, 9]), D('X1', [14.5, 9], [14.5, 13], { lab: 'l' }), W([14.5, 13], [14.5, 15]), R('R4', [14.5, 15], [17, 15], 4.7 * k, { lab: 'b' }),
      W([17, 15], [19, 15], [19, 11]), CE('C3', [17, 15], [17, 19], 10 * u, 'b', { lab: 'r' }), J([17, 15]), J([17, 19]),
      T('T2', 17, 11, 'AF116', { flip: true }), W([15.5, 9], [15.5, 5]), J([15.5, 5]), R('R5', [15.5, 5], [15.5, 1], 3.3 * k, { lab: 'l' }), W([15.5, 5], [19, 5], [19, 7]), R('R6', [19, 7], [23, 7], 27 * k, { lab: 't' }), W([23, 7], [25, 7], [25, 11]),
      W([15.5, 13], [15.5, 19]), J([15.5, 19]), W([19, 11], [19, 11]),
      T('T3', 23, 11, 'AC126'), W([24.5, 9], [24.5, 5]), J([24.5, 5]), LAMP('LA', [24.5, 5], [24.5, 1], { lab: 'r' }), W([24.5, 5], [21, 5], [21, 9]), R('R7', [21, 9], [21, 13], 27 * k, { lab: 'l' }), W([21, 13], [15.5, 13]), J([15.5, 13]),
      W([24.5, 13], [24.5, 15]), R('R8', [24.5, 15], [24.5, 19], 47, { lab: 'r' }), J([24.5, 19]),
      KEY('RK', [27, 19], [27, 14], { lab: 'r' }), W([27, 14], [27, 11], [25, 11]), J([25, 11]), W([25, 11], [21, 11]),
      CE('C4', [30, 19], [30, 1], 100 * u, 'a'), J([30, 1], [30, 19]),
    ] },
  });

  add({
    id: 'D4', group: 'D', ee8: false, pages: '32, 68',
    name: { en: 'Pilfering alarm', pt: 'Alarme antifurto' },
    text: {
      desc: { en: 'Sounds a whistling note when light falls on the LDR — for instance when a book lying on the cell is taken away, when a cupboard is opened or a train enters a tunnel. Can also be mounted on a door or window with two wires as a burglar alarm.', pt: 'Emite um apito quando a luz cai sobre o LDR — por exemplo quando um livro sobre a célula é retirado, quando um armário é aberto ou um trem entra num túnel. Também pode ser montado numa porta ou janela com dois fios, como alarme contra ladrões.' },
      assembly: { en: 'Diagram D4; terminals everywhere except A, S1, S3, S4, S6 and S7. Connect both AC 126 transistors correctly with their heat sinks. Insulated wires from the terminals to the switch contacts S3, S4, S6 and S7; LDR on the terminals marked LDR.', pt: 'Esquema D4; terminais em toda parte, exceto A, S1, S3, S4, S6 e S7. Ligue os dois AC 126 corretamente com seus dissipadores. Fios encapados dos terminais aos contatos S3, S4, S6 e S7; LDR nos terminais marcados LDR.' },
      use: { en: 'Slide the switch to the right and switch on: a whistling tone comes from the loudspeaker. Put your hands over the LDR: the tone stops. With the switch to the left the two wires at the left of the diagram are the alarm contacts: the loudspeaker is silent while they touch and whistles when they are separated.', pt: 'Chave à direita e ligue: sai um apito do alto-falante. Ponha as mãos sobre o LDR: o apito para. Com a chave à esquerda os dois fios à esquerda do esquema são os contatos do alarme: o alto-falante fica mudo enquanto se tocam e apita quando são separados.' },
      theory: { en: 'When light falls on the LDR it has a very low resistance and a small initial current through the base of T1 is amplified, goes through C2 to the base of T2, is amplified again and comes back through C1 to T1. This rapidly repeated process creates an alternating current that operates the loudspeaker. In the dark the LDR resistance is so high that practically no current can flow through the emitter of T1 and the whole thing stops.', pt: 'Quando a luz cai sobre o LDR ele tem resistência muito baixa e uma pequena corrente inicial na base de T1 é amplificada, passa por C2 à base de T2, é amplificada de novo e volta por C1 a T1. Esse processo repetido rapidamente cria uma corrente alternada que aciona o alto-falante. No escuro a resistência do LDR é tão alta que quase nenhuma corrente passa pelo emissor de T1 e tudo para.' },
      apps: { en: 'Book on the LDR in the shadow; toy train with a head lamp entering a tunnel; two drawing pins on a window frame as contacts.', pt: 'Livro sobre o LDR à sombra; trem de brinquedo com farol entrando num túnel; dois percevejos na janela como contatos.' },
    },
    controls: ['vol', 'light', 'slide', 'contact'], outputs: ['spk', 'scope'],
    layout: { w: 32, h: 21, el: [
      W([4, 1], [30, 1]), W([4, 19], [26, 19]), ...PSU(30),
      R('R1', [4, 1], [4, 6], 4.7 * k, { lab: 'l' }), W([4, 6], [4, 8]), J([4, 6]), W([4, 6], [7.5, 6]), R('R3', [7.5, 6], [7.5, 10], 680 * k, { lab: 'r' }), J([7.5, 6]), J([7.5, 10]),
      T('T1', 5.5, 10, 'AF116', { flip: true }), C('C1', [7.5, 10], [11, 10], 0.1 * u, { lab: 'b' }), W([11, 10], [11, 7], [15, 7], [15, 6]),
      W([4, 12], [4, 13]), R('R2', [4, 13], [4, 17], 270, { lab: 'l' }), W([4, 17], [4, 19]), J([4, 19]),
      LDR('LDR', [1, 15], [1, 19], { lab: 'l' }), W([1, 15], [1, 13], [4, 13]), J([4, 13]), W([1, 19], [4, 19]), J([1, 19]),
      T('T2', 17, 10, 'AC126'), W([18.5, 8], [18.5, 6]), J([18.5, 6]), SPK('LS', [18.5, 6], [18.5, 1], { lab: 'r' }), W([18.5, 12], [18.5, 14]),
      R('R4', [15, 6], [15, 10], 27 * k, { lab: 'l' }), J([15, 6]), W([15, 6], [18.5, 6]), J([15, 10]), C('C2', [12, 13], [15, 13], 0.1 * u, { lab: 'b' }), W([15, 13], [15, 10]), W([12, 13], [7.5, 13], [7.5, 10]),
      SL('S3-S7', [18.5, 14], [16.5, 16], [20.5, 16], { la: 'contact', lb: 'LDR' }), W([20.5, 16], [20.5, 17], [4, 17]), W([16.5, 16], [16.5, 19]), J([16.5, 19]), TERM([13, 16], 'A'), TERM([13, 18], 'B'), W([13, 16], [15, 16], [15, 17.5], [16.5, 17.5]),
      CE('C3', [23, 19], [23, 1], 100 * u, 'a'), J([23, 1], [23, 19]),
    ] },
  });

  add({
    id: 'D4.1', group: 'D', ee8: false, pages: '33, 69',
    name: { en: 'Pilfering alarm with power-economising circuit', pt: 'Alarme antifurto com circuito economizador' },
    text: {
      desc: { en: 'A variation on D4 with the advantage that it uses hardly any current in the rest state — the batteries last much longer. A third transistor watches the LDR and only then lets the two-transistor tone generator run.', pt: 'Uma variação do D4 com a vantagem de quase não consumir corrente em repouso — as pilhas duram muito mais. Um terceiro transistor vigia o LDR e só então deixa o gerador de tom de dois transistores funcionar.' },
      assembly: { en: 'Diagram D4.1. Read the D4 instructions again; this time there are two AC 126 (each with heat sink) and one AF 116, and the LDR is in a different place. The sliding switch works in reverse compared with D4.', pt: 'Esquema D4.1. Releia as instruções do D4; desta vez há dois AC 126 (cada um com dissipador) e um AF 116, e o LDR fica em outro lugar. A chave deslizante funciona ao contrário do D4.' },
      use: { en: 'Switch to the left: sensitive to light; switch to the right: signals the opening of doors or windows via two wires.', pt: 'Chave à esquerda: sensível à luz; chave à direita: sinaliza a abertura de portas ou janelas por meio de dois fios.' },
      theory: { en: 'So long as no light falls on the LDR its resistance is high and T3 draws no current, so no current flows in the collector of T2 and the generator T1/T2 is silent. When light falls on the LDR, T3 draws current, which starts T2 and T1 alternately as in D4, and the tone sounds.', pt: 'Enquanto não há luz no LDR sua resistência é alta e T3 não conduz, portanto não há corrente no coletor de T2 e o gerador T1/T2 fica mudo. Quando a luz cai no LDR, T3 conduz, o que faz T2 e T1 oscilarem alternadamente como no D4, e o tom soa.' },
      apps: { en: 'Compare the battery current in the rest state with D4 on the instrument panel.', pt: 'Compare a corrente das pilhas em repouso com o D4 no painel de instrumentos.' },
    },
    controls: ['vol', 'light', 'slide', 'contact'], outputs: ['spk', 'scope'],
    layout: { w: 32, h: 22, el: [
      W([4, 1], [30, 1]), W([4, 19], [26, 19]), ...PSU(30),
      R('R1', [4, 1], [4, 5], 4.7 * k, { lab: 'l' }), W([4, 5], [4, 8]), J([4, 5]), W([4, 5], [7, 5]), J([7, 5]), R('R3', [7, 5], [7, 8], 100 * k, { lab: 'r' }),
      T('T1', 5.5, 10, 'AC126', { flip: true }), W([7.5, 10], [7, 10], [7, 8]), J([7, 8]), CE('C1', [7, 8], [11, 8], 10 * u, 'a', { lab: 't' }), W([11, 8], [11, 6], [16, 6], [16, 8]),
      T('T2', 17.5, 10, 'AC126'), W([15.5, 10], [16, 10], [16, 8]), J([16, 8]), R('R5', [16, 8], [16, 5], 100 * k, { lab: 'r' }), W([16, 5], [19, 5]), J([19, 5]), W([19, 8], [19, 5]), SPK('LS', [19, 5], [19, 1], { lab: 'r' }),
      CE('C2', [11, 8], [11, 12], 10 * u, 'a', { lab: 'r' }), W([11, 12], [11, 13], [4, 13]), W([4, 12], [4, 13]), J([4, 13]), W([11, 8], [11, 8]),
      W([4, 13], [4, 14]), R('R2', [4, 14], [4, 19], 270, { lab: 'l' }), J([4, 19]),
      W([19, 12], [19, 13]), R('R6', [19, 13], [19, 19], 27 * k, { lab: 'r' }), J([19, 19]),
      W([4, 13], [4, 13]), T('T3', 13, 15, 'AF116'), W([14.5, 13], [19, 13]), J([19, 13]), W([14.5, 17], [14.5, 19]), J([14.5, 19]),
      LDR('LDR', [8, 15], [11, 15], { lab: 't' }), W([8, 15], [7, 15], [7, 17], [4, 17]), J([4, 17]),
      SL('S3-S8', [11, 18], [9, 20], [13, 20], { la: 'LDR', lb: 'contact' }), W([11, 18], [11, 15]), J([11, 15]), R('R4', [9, 20], [9, 22], 4.7 * k, { lab: 'l', noval: true }),
      TERM([15, 21], 'A'), W([13, 20], [15, 20], [15, 21]), TERM([17, 21], 'B'), W([17, 21], [17, 19]),
      CE('C3', [23, 19], [23, 1], 100 * u, 'a'), J([23, 1], [23, 19]),
    ] },
  });

  add({
    id: 'D5', group: 'D', ee8: false, pages: '33–34, 69',
    name: { en: 'Burglar alarm', pt: 'Alarme contra ladrões' },
    text: {
      desc: { en: 'When this alarm rings out it keeps on sounding until the reset key is pressed down. It works with light signals (LDR) or with switch contacts on doors and windows.', pt: 'Quando este alarme dispara, continua soando até que a tecla de rearme seja apertada. Funciona com sinais de luz (LDR) ou com contatos em portas e janelas.' },
      assembly: { en: 'Diagram D5, with the two keys mounted as for the electronic organ; a bare wire runs under the keys so that each key makes contact with it when pressed. Put the heat sinks on the two AC 126. Connect the loudspeaker and the LDR.', pt: 'Esquema D5, com as duas teclas montadas como no órgão eletrônico; um fio nu passa sob as teclas para que cada uma faça contato quando apertada. Ponha os dissipadores nos dois AC 126. Ligue o alto-falante e o LDR.' },
      use: { en: 'Sliding switch to the right: sufficient light on the LDR starts the whistling tone. Switch to the left: the tone begins when the left-hand (alarm) key is pressed — or when two wires on a window come into contact. In both cases the tone only stops when the right-hand (reset) key is pressed.', pt: 'Chave à direita: luz suficiente no LDR inicia o apito. Chave à esquerda: o apito começa quando a tecla da esquerda (alarme) é apertada — ou quando dois fios numa janela se tocam. Nos dois casos o apito só para quando a tecla da direita (rearme) é apertada.' },
      theory: { en: 'T2 and T3 generate the tone as in D4.1. The collector currents go through the loudspeaker and are fed back to the base of T2, and part of this current keeps T1 conducting: once started, the alarm holds itself on. The reset key short-circuits the feedback and the alarm stops.', pt: 'T2 e T3 geram o tom como no D4.1. As correntes de coletor passam pelo alto-falante e são realimentadas à base de T2, e parte dessa corrente mantém T1 conduzindo: uma vez disparado, o alarme se mantém. A tecla de rearme curto-circuita a realimentação e o alarme para.' },
      apps: { en: 'Window alarm with two drawing pins; light alarm at the front door; “trip wire” with the alarm key.', pt: 'Alarme de janela com dois percevejos; alarme de luz na porta; “fio de tropeço” com a tecla de alarme.' },
    },
    controls: ['vol', 'light', 'slide', 'akey', 'rkey', 'contact'], outputs: ['spk', 'scope'],
    layout: { w: 34, h: 22, el: [
      W([6, 1], [32, 1]), W([2, 19], [28, 19]), ...PSU(32),
      R('R2', [6, 1], [6, 5], 4.7 * k, { lab: 'l' }), W([6, 5], [6, 8]), J([6, 5]), W([6, 5], [9, 5]), R('R3', [9, 5], [12, 5], 27 * k, { lab: 't' }), W([12, 5], [12, 10]),
      T('T1', 7.5, 10, 'AF116', { flip: true }), W([9.5, 10], [12, 10]), J([12, 10]), R('R4', [12, 10], [15, 10], 100 * k, { lab: 'b' }),
      W([6, 12], [6, 13]), W([6, 13], [6, 19]), J([6, 19]), W([6, 13], [4, 13]), J([6, 13]),
      LDR('LDR', [4, 13], [4, 18], { lab: 'l' }), W([4, 18], [4, 19]), J([4, 19]), R('R1', [2, 19], [2, 13], 4.7 * k, { lab: 'l' }), W([2, 13], [4, 13]), J([4, 13]),
      SL('S3-S5', [2, 11], [0.8, 9], [3.2, 9], { la: 'key', lb: 'LDR' }), W([2, 11], [2, 13]), W([3.2, 9], [3.2, 7], [6, 7]), J([6, 7]),
      KEY('AK', [0.8, 9], [0.8, 4], { lab: 'r' }), W([0.8, 4], [0.8, 3], [6, 3]), J([6, 3]),
      R('R5', [15, 10], [15, 6], 100 * k, { lab: 'l' }), W([15, 6], [18.5, 6]), J([18.5, 6]), R('R6', [18.5, 6], [18.5, 1], 4.7 * k), T('T2', 17, 10, 'AC126'), W([18.5, 8], [18.5, 6]), W([18.5, 12], [18.5, 14]), R('R7', [18.5, 14], [18.5, 19], 270, { lab: 'r' }), J([18.5, 19]),
      CE('C2', [15, 10], [15, 14], 10 * u, 'a', { lab: 'r' }), W([15, 14], [15, 16], [12, 16], [12, 10]), J([15, 10]),
      J([18.5, 7]), C('C3', [18.5, 7], [21.5, 7], 0.1 * u, { lab: 'b' }), W([21.5, 7], [22.5, 7], [22.5, 10]), T('T3', 24.5, 10, 'AC126'), R('R8', [22.5, 10], [22.5, 6], 27 * k, { lab: 'l' }), W([22.5, 6], [26, 6]), J([26, 6]), W([26, 8], [26, 6]), SPK('LS', [26, 6], [26, 1], { lab: 'r' }), W([26, 12], [26, 19]), J([26, 19]),
      C('C1', [12, 1], [12, 3], 0.1 * u, { lab: 'r' }), W([12, 3], [12, 5]), J([12, 5]), J([12, 1]), W([15, 14], [15, 14]),
      KEY('RK', [21, 19], [21, 14], { lab: 'r' }), W([21, 14], [21, 13], [15, 13]), J([15, 13]),
      CE('C4', [29, 19], [29, 1], 100 * u, 'a'), J([29, 1], [29, 19]),
    ] },
  });

  // =========================================================================== E
  add({
    id: 'E1', group: 'E', ee8: true, pages: '34–35, 70',
    name: { en: 'Automatic night light', pt: 'Iluminação automática à noite' },
    text: {
      desc: { en: 'When the sun sets or the light in the room goes out, the emergency lighting switches on automatically; when the sun rises or the light is switched on again, the night light goes out again. The same principle controls street lighting and car-park lights.', pt: 'Quando o sol se põe ou a luz do cômodo apaga, a iluminação de emergência liga automaticamente; quando o sol nasce ou a luz volta a ser acesa, a luz noturna apaga. O mesmo princípio controla a iluminação pública.' },
      assembly: { en: 'Diagram E1, springs everywhere except S1 and L. Mount the resistors, the AF 116 (screening lead!) and the AC 126 with heat sink, then the lamp, the LDR on the two terminals top left and the battery wires (long strip to B−, short strip via red wire to S2).', pt: 'Esquema E1, molas em toda parte, exceto S1 e L. Monte os resistores, o AF 116 (terminal de blindagem!) e o AC 126 com dissipador, depois a lâmpada, o LDR nos dois terminais de cima à esquerda e os fios das pilhas (tira longa a B−, tira curta por fio vermelho a S2).' },
      use: { en: 'Switch on; nothing happens. Now switch off the light in the room, and the lamp goes on. To adjust the sensitivity, replace R2 by the potentiometer (insulated wires from the base of the AF 116 to P1 and from the bottom-left terminal to P2). In the simulator the potentiometer does exactly this.', pt: 'Ligue; nada acontece. Agora apague a luz do cômodo e a lâmpada acende. Para ajustar a sensibilidade, substitua R2 pelo potenciômetro (fios encapados da base do AF 116 a P1 e do terminal de baixo à esquerda a P2). No simulador o potenciômetro faz exatamente isso.' },
      theory: { en: 'So long as light falls on the LDR its resistance is low and the base of T1 is almost as negative as the collector: T1 conducts and the voltage lost in R3 leaves too little for the base of T2. In the dark the LDR resistance rises, T1 conducts less, the voltage on its collector — and on the base of T2 — grows, and T2 passes so much current that the lamp burns.', pt: 'Enquanto há luz no LDR sua resistência é baixa e a base de T1 fica quase tão negativa quanto o coletor: T1 conduz e a queda em R3 deixa muito pouco para a base de T2. No escuro a resistência do LDR sobe, T1 conduz menos, a tensão no seu coletor — e na base de T2 — cresce, e T2 deixa passar tanta corrente que a lâmpada acende.' },
      apps: { en: 'Automatic stair light; model railway station lights; connect a torch to the LDR to see the lamp dim gradually.', pt: 'Luz automática de escada; luzes de estação de ferromodelismo; aproxime uma lanterna do LDR para ver a lâmpada apagar gradualmente.' },
    },
    controls: ['vol', 'light'], outputs: ['lamp', 'scope'],
    layout: { w: 28, h: 21, el: [
      W([3, 1], [26, 1]), W([3, 19], [22, 19]), ...PSU(26),
      LDR('LDR', [3, 1], [3, 6], { lab: 'r' }), R('R1', [3, 6], [3, 9], 270, { lab: 'l' }), J([3, 6]), W([3, 9], [3, 10]), J([3, 10]), W([3, 10], [6, 10]),
      POT('R2', [3, 10], [3, 16], [5, 13], 10 * k, { lab: 'l' }), W([3, 16], [3, 19]), W([5, 13], [6, 13], [6, 16], [3, 16]), J([3, 16]), J([3, 19]),
      T('T1', 8, 10, 'AF116'), W([9.5, 8], [9.5, 6]), J([9.5, 6]), R('R3', [9.5, 6], [9.5, 1], 3.3 * k), W([9.5, 12], [9.5, 14]), R('R4', [9.5, 14], [9.5, 19], 47, { lab: 'l' }), J([9.5, 19]),
      R('R5', [9.5, 6], [14, 6], 2.2 * k, { lab: 't' }), W([14, 6], [14, 10]), T('T2', 16, 10, 'AC126'), W([17.5, 8], [17.5, 6]), LAMP('LA', [17.5, 6], [17.5, 1], { lab: 'r' }),
      W([17.5, 12], [17.5, 14]), R('R6', [17.5, 14], [17.5, 19], 4.7 * k, { lab: 'r' }), J([17.5, 19]),
      CE('C1', [22, 19], [22, 1], 100 * u, 'a'), J([22, 1], [22, 19]),
    ] },
  });

  add({
    id: 'E2', group: 'E', ee8: true, pages: '35–37, 70–71',
    name: { en: 'Rain and moisture indicator', pt: 'Indicador de umidade e chuva' },
    text: {
      desc: { en: 'A lamp lights up when the sensitive element becomes too wet. It can warn that the bath is getting too full, that a boat is leaking, or that the plants need water. Two bare wires are the sensing element.', pt: 'Uma lâmpada acende quando o elemento sensível fica úmido demais. Pode avisar que a banheira está enchendo, que um barco faz água ou que as plantas precisam de água. Dois fios desencapados são o elemento sensor.' },
      assembly: { en: 'Diagram E2: resistors, the 100 µF electrolytic (groove!), the AC 126 with heat sink and the AF 116. Connect the lamp and the batteries, and two wires with bared ends to the terminals of the base and collector of the AF 116.', pt: 'Esquema E2: resistores, o eletrolítico de 100 µF (ranhura!), o AC 126 com dissipador e o AF 116. Ligue a lâmpada e as pilhas, e dois fios com pontas desencapadas aos terminais da base e do coletor do AF 116.' },
      use: { en: 'Draw a thick pencil line on paper and press the wire ends on it: the lamp burns, brightest when the ends are close together. Wet newspaper, blotting paper, a flower pot, your two hands, tap water — all conduct. Distilled water and oil do not. Hands off the mains socket always!', pt: 'Faça um traço grosso de lápis no papel e encoste as pontas dos fios: a lâmpada acende, mais forte quando as pontas estão próximas. Jornal molhado, mata-borrão, vaso de planta, suas duas mãos, água da torneira — tudo conduz. Água destilada e óleo, não. Nunca mexa na tomada da rede!' },
      theory: { en: 'With the two wires apart the base of T1 is not connected and no current flows. A conductor between the wires connects the base to the negative collector voltage: T1 conducts, its emitter current through R1 makes the base of T2 negative, T2 draws current and the lamp lights. The more conductive the path, the brighter the lamp.', pt: 'Com os fios separados a base de T1 não está ligada e nenhuma corrente circula. Um condutor entre os fios liga a base à tensão negativa do coletor: T1 conduz, sua corrente de emissor por R1 torna negativa a base de T2, T2 conduz e a lâmpada acende. Quanto mais condutor o caminho, mais forte a lâmpada.' },
      apps: { en: 'Boat leak detector under the keel; laundry-dry indicator; automatic target for a water pistol; rectifying effect of a diode (with a 4 700 Ω resistor from base to collector); light meter with the LDR.', pt: 'Detector de vazamento sob a quilha; indicador de roupa seca; alvo automático para pistola de água; efeito retificador de um diodo (com resistor de 4 700 Ω entre base e coletor); fotômetro com o LDR.' },
    },
    controls: ['vol', 'probe'], outputs: ['lamp', 'scope'],
    layout: { w: 26, h: 21, el: [
      W([9.5, 1], [24, 1]), W([5, 19], [20, 19]), ...PSU(24),
      TERM([2, 4], 'c'), TERM([2, 8], 'b'), W([2, 4], [4, 4], [4, 2], [9.5, 2]), W([2, 8], [6, 8]), J([9.5, 2]),
      T('T1', 8, 8, 'AF116'), W([9.5, 6], [9.5, 2]), W([9.5, 2], [9.5, 1]), W([9.5, 10], [9.5, 12]), J([9.5, 12]), R('R1', [9.5, 12], [9.5, 19], 4.7 * k, { lab: 'l' }), J([9.5, 19]),
      W([9.5, 12], [12, 12]), R('R2', [12, 12], [12, 9], 4.7 * k, { lab: 'l' }), W([12, 9], [13, 9]),
      T('T2', 15, 9, 'AC126'), W([16.5, 7], [16.5, 6]), LAMP('LA', [16.5, 6], [16.5, 1], { lab: 'r' }), W([16.5, 11], [16.5, 13]), R('R3', [16.5, 13], [16.5, 19], 47, { lab: 'r' }), J([16.5, 19]),
      CE('C1', [20, 19], [20, 1], 100 * u, 'a'), J([20, 1], [20, 19]),
      { t: 'TXT', at: [2, 12], s: '', cls: 'small' },
    ] },
  });

  add({
    id: 'E3', group: 'E', ee8: false, pages: '37–38, 71',
    name: { en: 'Time switch', pt: 'Interruptor eletrônico de tempo' },
    text: {
      desc: { en: 'Times the period over which a lamp stays alight: with the potentiometer you make that time longer or shorter. Used for presetting the exposure time for printing photographs, and for time-regulated stair lighting.', pt: 'Mede o tempo durante o qual uma lâmpada fica acesa: com o potenciômetro esse tempo fica maior ou menor. Serve para ajustar o tempo de exposição na cópia de fotografias e para luz de escada temporizada.' },
      assembly: { en: 'Diagram E3; lamp, batteries, potentiometer and sliding switch on the board. Fix the electrolytic capacitors with the groove as shown, then the bare wires and transistors (heat sink on the AC 126!). Before connecting the batteries make sure the switch on the potentiometer is off.', pt: 'Esquema E3; lâmpada, pilhas, potenciômetro e chave deslizante na chapa. Fixe os eletrolíticos com a ranhura como mostrado, depois os fios nus e os transistores (dissipador no AC 126!). Antes de ligar as pilhas confira se a chave do potenciômetro está desligada.' },
      use: { en: 'Sliding switch to the left, switch on. Now slide to the right: the lamp glows and goes out after a short time. To get another flash, move the switch to the left first. For every knob position note the number of seconds with a stopwatch and make a little table — then you can set the time you want.', pt: 'Chave deslizante à esquerda, ligue. Agora passe à direita: a lâmpada acende e apaga depois de um tempo curto. Para outro ciclo, volte a chave à esquerda primeiro. Para cada posição do botão anote os segundos com um cronômetro e faça uma tabela — assim poderá ajustar o tempo desejado.' },
      theory: { en: 'With the switch to the right C1 and C2 are connected to the battery via R1 (potentiometer) and R3 and charge up. While they charge, the base of T1 is hardly negative, T1 does not conduct and T2 does: the lamp glows. When the capacitors are fully charged T1 conducts, T2 stops and the lamp goes out. Switching to the left short-circuits the capacitors, ready for the next timing.', pt: 'Com a chave à direita C1 e C2 ficam ligados às pilhas por R1 (potenciômetro) e R3 e se carregam. Enquanto carregam, a base de T1 mal fica negativa, T1 não conduz e T2 conduz: a lâmpada acende. Quando os capacitores estão carregados T1 conduz, T2 para e a lâmpada apaga. Passar a chave à esquerda curto-circuita os capacitores, prontos para a próxima contagem.' },
      apps: { en: 'Photographic enlarger timer; egg timer; stair light. Calibrate the knob with the stopwatch in the simulator.', pt: 'Temporizador de ampliador fotográfico; timer de ovo; luz de escada. Calibre o botão com o cronômetro do simulador.' },
    },
    controls: ['vol', 'slide'], outputs: ['lamp', 'stopwatch', 'scope'],
    layout: { w: 30, h: 22, el: [
      W([3, 1], [28, 1]), W([3, 19], [24, 19]), ...PSU(28),
      POT('R1', [3, 1], [3, 7], [5, 4], 10 * k, { lab: 'l' }), W([5, 4], [6, 4], [6, 7], [3, 7]), J([3, 7]), R('R2', [3, 7], [3, 19], 680 * k, { lab: 'l' }), J([3, 19]),
      W([3, 7], [7, 7]), J([7, 7]), R('R3', [7, 7], [10, 7], 27 * k, { lab: 't' }), W([10, 7], [11, 7], [11, 10]), J([11, 10]),
      CE('C1', [7, 7], [7, 11], 100 * u, 'b', { lab: 'l' }), CE('C2', [7, 11], [7, 15], 100 * u, 'b', { lab: 'l' }), W([7, 15], [7, 17]), J([7, 11]),
      SL('S3-S8', [7, 17], [5, 19], [9, 19], { la: 'reset', lb: 'time' }), W([5, 19], [3, 19]), W([9, 19], [11, 19]), J([9, 19]), J([5, 19]),
      W([7, 7], [7, 7]), W([7, 11], [9, 11], [9, 12], [11, 12]), W([11, 12], [11, 10]),
      T('T1', 13, 10, 'AC126'), W([14.5, 8], [14.5, 6]), J([14.5, 6]), R('R4', [14.5, 6], [14.5, 1], 27 * k, { lab: 'l' }), W([14.5, 12], [14.5, 15]), J([14.5, 15]), R('R6', [14.5, 15], [14.5, 19], 270, { lab: 'l' }), J([14.5, 19]),
      R('R5', [14.5, 6], [18.5, 6], 2.2 * k, { lab: 't' }), W([18.5, 6], [18.5, 10]), T('T2', 20.5, 10, 'AC126'), W([22, 8], [22, 6]), LAMP('LA', [22, 6], [22, 1], { lab: 'r' }),
      W([22, 12], [22, 15]), W([22, 15], [14.5, 15]), CE('C3', [18, 15], [18, 19], 10 * u, 'b', { lab: 'r' }), J([18, 15], [18, 19]), R('R7', [22, 15], [22, 19], 47, { lab: 'r' }), J([22, 19]), J([22, 15]),
      CE('C4', [25, 19], [25, 1], 100 * u, 'a'), J([25, 1], [25, 19]),
    ] },
  });

  add({
    id: 'E4', group: 'E', ee8: false, pages: '38–40, 71–72',
    name: { en: 'Universal measuring equipment', pt: 'Aparelho universal de medições' },
    text: {
      desc: { en: 'Measures resistors and capacitors whose value is unknown, and the intensity of light with the LDR. Not as accurate as laboratory equipment, but accurate enough for our purposes: it compares the unknown part X with a standard S.', pt: 'Mede resistores e capacitores de valor desconhecido e a intensidade da luz com o LDR. Não é tão preciso quanto um aparelho de laboratório, mas o bastante para os nossos fins: compara a peça desconhecida X com um padrão S.' },
      assembly: { en: 'Diagram E4; terminals everywhere except S1+P1, P2 and P3. When the potentiometer switch is off the pointer of the knob must be exactly above the first line on the scale. Three terminals at the bottom left: the standard S goes between the first and second, the unknown X between the second and third. Listen with the earphone.', pt: 'Esquema E4; terminais em toda parte, exceto S1+P1, P2 e P3. Com a chave do potenciômetro desligada o ponteiro do botão deve ficar exatamente sobre a primeira linha da escala. Três terminais embaixo à esquerda: o padrão S entre o primeiro e o segundo, o desconhecido X entre o segundo e o terceiro. Ouça pelo fone.' },
      use: { en: 'Switch on: a whistling tone. Turn the knob until the tone disappears and read the scale. Pointer on 10 with a 1 500 Ω standard: the unknown resistor is 15 000 Ω; on 0.1 it is 150 Ω. Capacitors are measured the same way (the ratio reads the other way round). Two known resistors of 100 Ω and 10 000 Ω cover the whole range.', pt: 'Ligue: um apito. Gire o botão até o apito desaparecer e leia a escala. Ponteiro em 10 com um padrão de 1 500 Ω: o resistor desconhecido é 15 000 Ω; em 0,1 é 150 Ω. Capacitores medem-se do mesmo modo (a relação lê-se ao contrário). Dois resistores conhecidos de 100 Ω e 10 000 Ω cobrem toda a faixa.' },
      theory: { en: 'T1 generates a tone (C1, C2, C3 feed part of the collector current back to the base) and T2 amplifies it. The current from T2 flows two ways: through the potentiometer and through S and X in series — a measuring bridge. When the ratio of S to X equals the ratio of the two halves of the potentiometer, points A and B have the same voltage and the earphone is silent. The scale is marked with these ratios.', pt: 'T1 gera um tom (C1, C2, C3 realimentam parte da corrente de coletor à base) e T2 o amplifica. A corrente de T2 segue dois caminhos: pelo potenciômetro e por S e X em série — uma ponte de medição. Quando a relação entre S e X é igual à relação entre as duas metades do potenciômetro, os pontos A e B têm a mesma tensão e o fone fica mudo. A escala é marcada com essas relações.' },
      apps: { en: 'Light meter: the LDR replaces X; compare its resistance with a normal resistance at various light intensities. Sort the resistors of the kit without reading the colour code.', pt: 'Fotômetro: o LDR substitui X; compare sua resistência com uma normal em várias intensidades de luz. Separe os resistores do conjunto sem ler o código de cores.' },
    },
    controls: ['vol', 'unknown'], outputs: ['ear', 'scope'],
    layout: { w: 32, h: 22, el: [
      W([4, 1], [30, 1]), W([4, 18], [26, 18]), BAT([30, 1], [30, 18]), SW('S1S2', [26, 18], [28, 18]), W([28, 18], [30, 18]), TXT([26, 19.2], 'S1', { cls: 'small' }), TXT([28, 19.2], 'S2', { cls: 'small' }),
      C('C1', [4, 4], [8, 4], 47 * n, { lab: 't' }), W([4, 4], [4, 8]), J([4, 8]), W([8, 4], [10, 4]), J([10, 4]),
      C('C2', [4, 8], [7, 8], 47 * n, { lab: 't' }), J([7, 8]), C('C3', [7, 8], [10, 8], 47 * n, { lab: 't' }), R('R3', [10, 8], [13, 8], 4.7 * k, { lab: 't' }), J([13, 8]),
      R('R1', [4, 8], [4, 14], 4.7 * k, { lab: 'l' }), R('R2', [7, 8], [7, 14], 4.7 * k, { lab: 'l' }), W([4, 14], [4, 18]), W([7, 14], [7, 18]), J([4, 18], [7, 18]),
      R('R4', [10, 4], [10, 8], 680 * k, { lab: 'l' }), W([10, 4], [13, 4]), J([13, 4]),
      T('T1', 15, 8, 'AC126'), W([16.5, 6], [16.5, 4]), W([13, 4], [16.5, 4]), J([16.5, 4]), R('R5', [16.5, 4], [16.5, 1], 4.7 * k), W([16.5, 10], [16.5, 18]), J([16.5, 18]),
      C('C4', [16.5, 4], [19, 4], 0.1 * u, { lab: 't' }), W([19, 4], [20, 4], [20, 7]), T('T2', 22, 7, 'AC126'), W([23.5, 5], [23.5, 1]), J([23.5, 1]), W([23.5, 9], [23.5, 11]), J([23.5, 11]),
      R('R6', [20, 7], [20, 4], 330 * k, { lab: 'l', noval: true }), CE('C5', [23.5, 11], [23.5, 15], 10 * u, 'a', { lab: 'r' }), W([23.5, 15], [23.5, 18]), J([23.5, 18]),
      // bridge
      W([23.5, 11], [12, 11]), J([12, 11]), R('S', [12, 11], [12, 14], 1.5 * k, { lab: 'l', noval: true }), R('X', [12, 14], [12, 17], 0, { lab: 'l', noval: true }), J([12, 14]), W([12, 17], [12, 18]), J([12, 18]),
      POT('R7', [19, 11], [19, 17], [17, 14], 10 * k, { lab: 'r' }), W([19, 11], [23.5, 11]), W([19, 17], [19, 18]), J([19, 18]),
      EAR('EAR', [12, 14], [17, 14], { lab: 'b' }), TXT([12.6, 13.4], 'A', { cls: 'small' }), TXT([17.6, 13.4], 'B', { cls: 'small' }),
      CE('C6', [26, 18], [26, 1], 100 * u, 'a'), J([26, 1]), W([23.5, 18], [26, 18]),
    ] },
  });

  // ---- helper: list of components for the Parts tab ---------------------------
  const PART_TYPES = ['R', 'C', 'CE', 'T', 'D', 'L', 'LDR', 'LAMP', 'P', 'VC', 'KEY', 'SL', 'SPK', 'EAR', 'MIC', 'PU', 'BAT'];
  function partsOf(c) {
    return c.layout.el.filter(e => PART_TYPES.includes(e.t) && (e.id || e.t === 'BAT')).map(e => ({ id: e.id || 'B', t: e.t, v: e.v, typ: e.typ }))
      .sort((a, b) => (PART_TYPES.indexOf(a.t) - PART_TYPES.indexOf(b.t)) || a.id.localeCompare(b.id, undefined, { numeric: true }));
  }
  const byId = {}; CIRCUITS.forEach(c => { byId[c.id] = c; });
  EE.circuits = { list: CIRCUITS, byId, partsOf };
})(window.EE20);
